### ISSUE TITLE
Compilers should be deterministic: same source code in C# should generate same assembly binary regardless of other referenced assemblies

### ISSUE THREAD

**Issue by Shahyads** [dotnet/roslyn#11087]
**Version Used**: 
all versions
**Steps to Reproduce**:

1. create project ClassLibrary1.csproj outputs a.dll containing class A as follows
```
namespace ClassLibrary1
{
    public class A
    {
        public void M1(int x = 2)
        {

        }
    }
}
```
14. create project ClassLibrary2.csproj references a.dll outputs b.dll containing Class B as follows
```
using ClassLibrary1;

namespace ClassLibrary2
{
    public class B
    {
        void M2(A a)
        {
            a.M1();
        }
    }
}
```
29. Build All and copy the b.dll file somewhere
30. Change Class A as follows
```
namespace ClassLibrary1
{
    public class A
    {
        public void M1(int x = 33)
        {

        }
    }
}
```
43. Rebuild All
44. Compare IL's generated for Method M2 of Class B in b.dll with the previous copy.
45. 

**Expected Behavior**:
The output assembly of ClassLibrary2 (b.dll) Must not Change. Because its source code has no change. 
I think the default values should provided in ClassLibrary1 (a.dll) at compile time. But passing the default values to Callee Must not hard coded in Caller IL (method M2 of class B) at compile time. The default values should extract and passed later in link time or run time.

**Actual Behavior**:
the source code of ClassLibrary2 is the same. However, the resulting output assemly (b.dll) is not the same.

**Comment by HaloFour** [comment]
@Shahyads

The default value for an optional parameter is always embedded in the caller.  If you didn't recompile `b.dll` and you executing that code the value of `x` would be `2`, not `33`.  This behavior is by design.

**Comment by Shahyads** [comment]
@HaloFour 
Yes I know but its another example of the following issue:
Compilers should be deterministic: same inputs generate same outputs #372

**Comment by HaloFour** [comment]
@Shahyads

Referenced assemblies are inputs, and in this case they have changed.

**Comment by Shahyads** [comment]
@HaloFour 
I had expected such answers. You are right. The referenced assemblies are inputs too. And we can accept the Roslyn as a deterministic compiler by the definition "same inputs generate same outputs".

The more important question is "Why should Compilers be deterministic?"
Build Engineers love compilers which assure this rule: "same source codes generates same binaries"

**Comment by HaloFour** [comment]
Either way, that's how optional arguments work and how they have worked since .NET 1.0.  The optional parameter is simply marked as optional in the parameter metadata and the default value serialized in the assembly BLOB stream.  It is then up to a supporting compiler to identify that `[opt]` flag on the parameter, extract the default value and embed it at the call site.  The changed reference is expected to cause the resultant assembly to be different.

A build engineer should expect that changing the referenced assemblies will change the resultant assembly.  Optional parameters aside there are many other such examples of how this could arise.  The referenced assembly could have a different assembly version or public key token.  A referenced type could be moved to a different namespace which happens to already be in scope in the consumed source.  As long as the binary of the referenced assembly is different then it can't be expected that the resultant assembly will match that of a previous compilation.

**Comment by Shahyads** [comment]
@HaloFour @KirillOsenkov 
Thank you. While Roslyn compiles in this way, a build engineer had to expect that changing the referenced assemblies will change the resultant assembly. 
I submitted this issue for changing the way Roslyn compiles the assemblies. I think dotNet/C# compilers do move some linker responsibilities to compile time by cost of loosing determinism. I know it is by design. However, it would be better, if the Design were more deterministic.
Regards,
Shahyad

**Comment by jmarolf** [comment]
@Shahyads The problem is that changing this particular behavior for optional parameters would break existing code.  Even if we came up with a new implementation for optional parameters that did what you wanted, optional parameters in existing assemblies would need to be treated the same.

**Comment by HaloFour** [comment]
Not to mention that would not address the other myriad of situations in which a change to a reference assembly could affect the final metadata and/or IL of compiled source:

1. Assembly version could change
1. Assembly public token could change
1. Target type could be moved to a different namespace that happens to already be in scope
1. Target type could be changed from a `class` to a `struct`, or vice versa
1. Target type could be outright changed, if it is the return value of another method and the consumer is using type inference
1. Target method could be converted to a generic method using generic type inference based on the arguments, or vice versa
1. Target method could be removed outright and replaced by an extension method that happens to already be in scope, or vice versa
1. Target method parameter could be changed to a different type that allows an implicit widening conversion (e.g. `int` to `long`)
1. Target method parameter could be changed to a different type that defines an implicit conversion operator

The metadata of a reference is just as critical as the source itself.  If that metadata changes then the inputs to the compilation have been changed and it is unreasonable to expect the output to match that of a previous compilation.

**Comment by Shahyads** [comment]
@HaloFour @gafter 
Thank you for your attention. I had got the deep problem. For more elaboration of this issue you can add these items too.
10. A referenced type could be moved to a different namespace which happens to already be in scope in the consumed source.
11. A referenced type could be moved to a different Inheritance hierarchy.
12. Non virtual methods of parent class could be moved to a different level in the inheritance path.
etc. 
I think In other compilers like C++  these type of "Meta Data" is minimal and transferred  through header files which are some sort of source code and all changes in the header file is considered  changes in source codes of caller not the referenced binaries.
I'm not good at English. Hope you have got it. It's too fundamental to be completely solved in dotNet. However, some of these issues which is more probable to occur could be resolved.
By the way,  the more determinism(same source codes generates same binaries) the more happy build engineers, the more simple configuration management, the easier build scripts, and the more idle build machines :)

Regards,
Shahyad

**Comment by Shahyads** [comment]
@HaloFour @gafter 
Today, I found that I was wrong. And this level of determinism provided by "/deterministic" flag is good enough.
thank you all.

**Comment by paulomorgado** [comment]
@HaloFour, you forgot `const` fields. They have the same characteristics as optional argument values. They become hardcoded in the call site.
