### ISSUE TITLE
Error in MSBuildWorkspace.OpenSolutionAsync: "exePath must be specified when not running inside a stand alone exe"

### ISSUE THREAD

**Issue by kurtgronbech** [dotnet/roslyn#21799]
I have upgraded to Visual Studio 2017 version 15.3.3,  ASP.NET Core 2.0 SDK, and Microsoft.CodeAnalysis version 2.3.1 referenced in a project. 

I'm no longer able to open any solution/workspace (.SLN) with MSBuildWorkspace.OpenSolutionAsync. 

This was working just fine before the upgrade, with  VS 2017 version 15.1, ASP.NET Core 1.1 SDK, and Microsoft.CodeAnalysis version 2.3.0. 

Code: 

```
workspace = MSBuildWorkspace.Create();			
solution = workspace.OpenSolutionAsync(@"c:\dev\test\test.sln").Result;
```

workspace.Diagnostics contains an error message with "exePath must be specified when not running inside a stand alone exe" for each project. 

`{[Failure] Msbuild failed when processing the file 'C:\dev\test\test.web\test.web.csproj' with message: exePath must be specified when not running inside a stand alone exe.}
`

Any ideas what the root cause may be? I suspect it may be a configuration issue with MsBuild, but I have searched and tried many things for hours on end without being able to fix the issue. 

**Version Used**: 

Microsoft.Build version 15.3.409
Microsoft.CodeAnalysis version 2.3.1

**Steps to Reproduce**:

1. Install VS 2017 version 15.3.3
2. Install ASP.NET Core 2.0 SDK
3. Create new project (any type of project). I have created a default ASP.NET MVC project. 
4. Add a reference to NuGet packages Microsoft.Build version 15.3.409 and Microsoft.CodeAnalysis version 2.3.1
5. Try to open any .SLN with the code above

**Expected Behavior**:

Open should work without any errors in workspace.Diagnostics.

**Actual Behavior**:

Errors are shown in workspace.Diagnostics.

**Comment by dpoeschl** [comment]
@jasonmalinowski Any idea what might be going on here?

**Comment by jasonmalinowski** [comment]
@dpoeschl It looks like that message might be thrown by the .NET configuration API if it can't figure out which executable it should be reading the app.config for. But who is reading it now that wasn't before I'd have to dig.

**Comment by jasonmalinowski** [comment]
@DustinCampbell Just to check, you haven't already fixed this by chance with the work you're doing on MSBuildWorkspace right now?

**Comment by DustinCampbell** [comment]
I don't *think* I've fixed this, since I haven't ever seen that error.

**Comment by kurtgronbech** [comment]
I'm back looking at this issue again. Here's the call stack after catching an exception on 

`Microsoft.Build.Evaluation.ProjectCollection.GlobalProjectCollection.UnloadAllProjects();`

Call stack: 

```
   at System.Configuration.ConfigurationManager.OpenExeConfigurationImpl(ConfigurationFileMap fileMap, Boolean isMachine, ConfigurationUserLevel userLevel, String exePath, Boolean preLoad)
   at Microsoft.Build.Evaluation.ToolsetConfigurationReader.ReadApplicationConfiguration()
   at Microsoft.Build.Evaluation.ToolsetConfigurationReader.get_ConfigurationSection()
   at Microsoft.Build.Evaluation.ToolsetConfigurationReader.<get_ToolsVersions>d__8.MoveNext()
   at Microsoft.Build.Evaluation.ToolsetReader.ReadEachToolset(Dictionary`2 toolsets, PropertyDictionary`1 globalProperties, PropertyDictionary`1 initialProperties, Boolean accumulateProperties)
   at Microsoft.Build.Evaluation.ToolsetReader.ReadToolsets(Dictionary`2 toolsets, PropertyDictionary`1 globalProperties, PropertyDictionary`1 initialProperties, Boolean accumulateProperties, String& msBuildOverrideTasksPath, String& defaultOverrideToolsVersion)
   at Microsoft.Build.Evaluation.ToolsetReader.ReadAllToolsets(Dictionary`2 toolsets, ToolsetRegistryReader registryReader, ToolsetConfigurationReader configurationReader, PropertyDictionary`1 environmentProperties, PropertyDictionary`1 globalProperties, ToolsetDefinitionLocations locations)
   at Microsoft.Build.Evaluation.ProjectCollection.InitializeToolsetCollection(ToolsetRegistryReader registryReader, ToolsetConfigurationReader configReader)
   at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties, IEnumerable`1 loggers, IEnumerable`1 remoteLoggers, ToolsetDefinitionLocations toolsetDefinitionLocations, Int32 maxNodeCount, Boolean onlyLogCriticalEvents)
   at Microsoft.Build.Evaluation.ProjectCollection.get_GlobalProjectCollection()
   at TestOpenAspNetCore20.Controllers.HomeController.Index()
```

So it looks like it is the exePath parameter in 
System.Configuration.ConfigurationManager.OpenExeConfigurationImpl which is the problem. Related to ToolsetReader..

Any ideas about what's going on? 

Note: This is just one way I'm able to get an insight into what's going on, and is not only related to UnloadAllProjects. I'm still unable to load any projects without workspace.Diagnostics complaining about the same error. 

I still suspect a configuration problem on my computer.

**Comment by kurtgronbech** [comment]
Seems related to all of these

https://github.com/Microsoft/msbuild/issues/2369
https://github.com/Microsoft/msbuild/issues/2310
https://github.com/Microsoft/msbuild/issues/2427
https://github.com/dotnet/roslyn/issues/15056
https://github.com/dotnet/roslyn/issues/21583
https://github.com/dotnet/roslyn/issues/21275

All of these solutions/workarounds works for me: 

**Workaround 1)** 

Setting MSBUILD_EXE_PATH in code: 

`Environment.SetEnvironmentVariable("MSBUILD_EXE_PATH", @"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe");`

**Workaround 2)** 

Setting VSINSTALLPATH in code: 

`Environment.SetEnvironmentVariable("VSINSTALLDIR", "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community");`

**Workaround 3)** 

Andy Gerlicher has created an MSBuildLocator library, mentioned towards the bottom in [this](https://github.com/Microsoft/msbuild/issues/2369) thread

Package: https://dotnet.myget.org/feed/msbuild/package/nuget/Microsoft.Build.MSBuildLocator
Source: https://github.com/Microsoft/MSBuildLocator/

Which we for example can use like this: 

```
var instances = MSBuildLocator.QueryVisualStudioInstances().ToList();
var instanceToUse = instances.First(a => a.Version.Major == 15); 
Environment.SetEnvironmentVariable("VSINSTALLDIR", instanceToUse.VisualStudioRootPath);
```

It did NOT work for me with 

`MSBuildLocator.RegisterDefaults();`

or only 

`MSBuildLocator.RegisterInstance(instanceToUse);`

So I had to do Environment.SetEnvironmentVariable("VSINSTALLDIR", instanceToUse.VisualStudioRootPath) and I haven't looked into that any more yet.

**Comment by raffaeler** [comment]
I tried the latest 2.6.0-beta3 packages, but it still fails loading the solution with the following errors (one per-project)
I only set the VSINSTALLDIR to C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise

The WorkspaceFailed event gave these errors:
```
[Failure] Msbuild failed when processing the file 'H:\dev\Samples\Example1\Example1.csproj'
with message: Invalid static method invocation syntax: 
"[MSBuild]::IsRunningFromVisualStudio()". Method '[MSBuild]::IsRunningFromVisualStudio' not found.
 Static method invocation should be of the form: $([FullTypeName]::Method()), e.g. $([System.IO.Path]::Combine(`a`, `b`)).   C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets

[Failure] Msbuild failed when processing the file 'H:\dev\Samples\Example2\Example2.csproj'
with message: Invalid static method invocation syntax:
"[MSBuild]::IsRunningFromVisualStudio()". Method '[MSBuild]::IsRunningFromVisualStudio' not found. 
Static method invocation should be of the form: $([FullTypeName]::Method()), e.g. $([System.IO.Path]::Combine(`a`, `b`)).   C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets
```

Any hint?

**Comment by kurtgronbech** [comment]
@raffaeler Try upgrading to Microsoft.Build v15.5.180 from Nuget. That should fix that error message.

**Comment by raffaeler** [comment]
Thank you @kurtgronbech 
The WorkspaceFailed event is still blaming failures, but the solution was loaded.
Should I worry about these ones?
```
[Failure] Msbuild failed when processing the file 'H:\dev\Samples\Example1\Example1.csproj' with message: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets: (84, 5): The "Csc" task could not be instantiated from the assembly "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn\Microsoft.Build.Tasks.CodeAnalysis.dll". Please verify the task assembly has been built using the same version of the Microsoft.Build.Framework assembly as the one installed on your computer and that your host application is not missing a binding redirect for Microsoft.Build.Framework. Unable to cast object of type 'Microsoft.CodeAnalysis.BuildTasks.Csc' to type 'Microsoft.Build.Framework.ITask'.
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets: (84, 5): The "Csc" task has been declared or used incorrectly, or failed during construction. Check the spelling of the task name and the assembly name.

[Failure] Msbuild failed when processing the file 'H:\dev\Samples\Example2\Example2.csproj' with message: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets: (1601, 5): The "GetReferenceNearestTargetFrameworkTask" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin" directory.
```

**Comment by kurtgronbech** [comment]
@raffaeler I'm not sure about the first one and I'm getting a similar error as the second one with the GetReferenceNearestTargetFrameworkTask when I try to build a project. 

The only things I can think of for the first error is maybe try upgrading to Visual Studio 5.5.1 and Microsoft.CodeAnalysis 2.6.0 if you haven't, maybe try to set MSBUILD_EXE_PATH to C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe in addition to VSINSTALLDIR, maybe try assembly binding for Microsoft.Build.Framework in your web.config

```
 <dependentAssembly>
        <assemblyIdentity name="Microsoft.Build.Framework" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-15.1.0.0" newVersion="15.1.0.0" />
      </dependentAssembly>
```
Maybe some experts in this forum can advice what the root cause and correct solution or workaround is. 

Yesterday I created a post on Stackoverflow regarding the error with GetReferenceNearestTargetFrameworkTask: 

[Link to post on Stackoverflow](https://stackoverflow.com/questions/47763669/ms-build-15-the-nuget-build-tasks-getreferencenearesttargetframeworktask-tas)

Here is what my error message looks like: 

> The "NuGet.Build.Tasks.GetReferenceNearestTargetFrameworkTask" task could not be loaded

Full error: 

> ERROR C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1601,5): The "NuGet.Build.Tasks.GetReferenceNearestTargetFrameworkTask" task could not be loaded from the assembly C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.Build.Tasks.dll. Could not load file or assembly 'Microsoft.Build.Framework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. Confirm that the declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. Done building project "CMS.csproj" -- FAILED

I'm currently stuck on this and not sure where to go from here.

**Comment by raffaeler** [comment]
I already updated the Roslyn packages to 2.6 together with the MSBuild ones.
Since the beginning I set the following env variables:
- VisualStudioVersion
- MSBUILD_EXE_PATH
- VSINSTALLDIR

I tried with both the VS2017 RTM (15.5.1) and VS2017 Preview (15.6.0 Preview 1.0) but I get the same errors.

I have no idea why ...

**Comment by raffaeler** [comment]
It's getting worse and worse.
Now I load a solution and one of the three projects fails the compilation. The reason is the missing references.
The `MSBuildWorkspace.OpenSolutionAsync` did not fill the project references only for that specific project. 
I tried switching msbuild version from 2017 to 2015 and I get different errors  but the references are loaded correctly.
Can someone enlight me what is going on here? TIA

**Comment by jasonmalinowski** [comment]
Closing as stale since there's nothing actionable at this point with any more recent code. (Maybe I could install all the old versions but that's not a great use of time...)
