### ISSUE TITLE
Awaiting methods or delegates cause code completion to fail when the invocation expression is an identifier name

### ISSUE THREAD

**Issue by ChristopherHaws** [dotnet/roslyn#22416]
In editors that use Roslyn (Visual Studio, VSCode, LINQPad, etc), code completion fails when invoked prior to an awaited `InvocationExpressionSyntax` who's expression is an `IdentifierNameSyntax`.

**Version Used**: 
Visual Studio Enterprise 2017 15.4.0 Preview 3.0
Visual Studio Enterprise 2017 15.3.5
VSCode 1.17.0-insider
LINQPad 5.23.03

**Steps to Reproduce**:
1. Create a new class library (.NET Core or .NET Framework, it happens in both)
2. Replace Class1 with the following code:
```csharp
using static System.Threading.Tasks.Task;

public class Class1
{
    public delegate Task TestDelegate(String arg);

    public async Task InvokeDelagateAsync(String arg, TestDelegate next)
    {
        // Type 'arg.' and hit ctrl+space (Edit.CompleteWord) here

        await next(arg);
    }

    public async Task InvokeMethodAsync(String arg)
    {
        // Type 'arg.' and hit ctrl+space (Edit.CompleteWord) here

        await TestMethodAsync();
    }

    public async Task InvokeStaticMethodAsync(String arg)
    {
        // Type 'arg.' and hit ctrl+space (Edit.CompleteWord) here

        await Delay(1);
    }

    private Task TestMethodAsync() => Task.CompletedTask;
}
```
3. Create a line before any of the `await` calls and type `arg.`

**Expected Behavior**:
Code completion should show up for the `arg` string type and the following error should be in the errors window:
```
Severity    Code    Description
Error       CS1001  Identifier expected
Error       CS1002  ; expected
```

**Actual Behavior**:
The code completion window does not appear and the following errors are in the errors window:
```
Severity    Code    Description
Error       CS4003  'await' cannot be used as an identifier within an async method or lambda expression
Error       CS1001  Identifier expected
Error       CS0118  'arg' is a variable but is used like a type
Error       CS0136  A local or parameter named 'next' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter
Error       CS0501  'next(arg)' must declare a body because it is not marked abstract, extern, or partial
Error       CS0118  'arg' is a variable but is used like a type
```

**Additional Observations**:
- This issue does not occur when calling `await next.Invoke(arg);` instead of `await next(arg);`
- This issue does not occur when calling `await this.TestMethodAsync(arg);` instead of `await TestMethodAsync(arg);`
- This issue does not occur when calling `await Task.Delay(1);` instead of `await Delay(1);`
- This issue does not occur when calling synchronous delegates or methods.
- This issue occurs regardless of whether there are args getting passed to the method/delegate or not

**Developer Community Report**:
https://developercommunity.visualstudio.com/content/problem/122036/invoking-async-delegates-cause-code-completion-to.html

**Comment by ChristopherHaws** [comment]
Updated the title and description of the issue to be more specific about what is failing.

**Comment by dpoeschl** [comment]
`arg` shows up in the completion list for me at that location when running a build from the latest Roslyn codebase:

![image](https://user-images.githubusercontent.com/235241/31145159-d0296384-a837-11e7-8d7a-64eb0ef9bccd.png)

Does that look like what you want from a completion list?

**Comment by dpoeschl** [comment]
Adding "Area-Compilers" and tagging @jaredpar for the question about the set of errors produced in this situation.

**Comment by ChristopherHaws** [comment]
I also found another case where this occurs. When awaiting a method from inside a lambda. This one is a bit different because it only seems to occur when the arg has a property that you are trying to access.

```csharp
public class Class1
{
	public delegate Task StreamDelegate(Fake arg);
	public void Run(StreamDelegate delagate) {}

	public void AsyncLambda()
	{
		this.Run(async (arg) =>
		{
			// Type 'arg.Stream.' and hit ctrl+space (Edit.CompleteWord) here
			//arg.Stream.
			await arg.Stream.WriteAsync("");
		});
	}

	public class Fake
	{
		public StreamWriter Stream { get; set; }
	}
}
```

**Comment by tvand7093** [comment]
I was able to reproduce the error in VS Pro 15.3.5, but it seems to work fine (shows the completion list correctly as @ChristopherHaws expected) using the latest master branch. Perhaps this has been fixed?

**Comment by ChristopherHaws** [comment]
I just did a fresh install of the latest Visual Studio 2017 (15.5 Preview 1) using Roslyn Language Services 2.6.0.6220501 and the code completion issue seems to be fixed, but the errors that appear are still wrong.

![image](https://user-images.githubusercontent.com/5934505/31561688-8867feec-b00d-11e7-89aa-15af3486c9c7.png)

**Comment by CyrusNajmabadi** [comment]
We improved this through better recognition in teh intellisense engine about what is going on.  The problem is that this code is *fundamentally* ambiguous at the parsing stage.   The parser can see this and can reasonably think that its' seeing a local function declaration that looks like:

```c#
arg.await next(arg
```

i.e. similar to a local function like:

```c#
int myLocalFunction(String
```

We can't determine what is actually going on at parse time without a lot of additional complexity and expensive lookahead.  So we just parse a local function (and thus have tons of later cascading errors), and we allow intellisense to look for this sort of thing and give proper intellisense.

--

While it would be nice for the errors to be improved, it's not critical and is inline with tons of other scenarios where parse ambiguities can lead to cascaded problems in partially written code.  i.e. it doesn't need to be fixed unless it is actually impacting a scenario like intellisense.

**Comment by sharwell** [comment]
Duplicate of #4474
