### ISSUE TITLE
Code fixes shouldn't be offered for rude edits

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn#26218]
**Version Used**: 

**Steps to Reproduce**:

1. Create a console app with following code:
```C#
class C { }

class Program // : C 
{
    static void Main(string[] args)
    { 
    }
}
```

2. Start debugging (F10)
3. Uncomment `// : C`
4. Rude edit shows up, hover over the purple squiggle:
![image](https://user-images.githubusercontent.com/41759/38903349-30a6de88-4259-11e8-9ec2-bb260e041c17.png)

**Expected Behavior**:

- "Show potential fixes" should not be displayed. 

**Actual Behavior**:

- "Show potential fixes" is displayed and suggests "Add accessibility modifier" as a potential fix.

**Comment by tmat** [comment]
@heejaechang Do we suggest potential fixes for all kinds of diagnostics?

**Comment by heejaechang** [comment]
@tmat no, I think in that line, there is suggestion, somewhere that is intersect with rude edit diagnostics.

don't do debugging, and see whether you get code fix there.

**Comment by CyrusNajmabadi** [comment]
Please don't make this change.  I make edits all the time during EnC sessions, and i absolutely hate when features are randomly disabled during debugging.

**Comment by tmat** [comment]
@CyrusNajmabadi This UI doesn't make any sense as is today. The "Show potential fixes" shows up for an EnC diagnostic that there are no fixes available for. It leads the user to thinking that they can get rid of the rude edit by applying the fix, which is not true.

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi This UI doesn't make any sense as is today. "Show potential fixes" shows up for an EnC diagnostic that there are no fixes available for

This is the case already today for any compiler errors that also are paired with any style diagnostics.  The lightbulb is for all issues on the line, not just EnC or compiler errors.  If i want to go and use the lightbulb to add accessibility modifiers for a type i've created, i shouldn't be prevented just because there was an error from another component at the same location.

**Comment by heejaechang** [comment]
@tmat @CyrusNajmabadi @kuhlenh @jinujoseph 

I think this is another design issue. 

so, it looks like the diagnostic IDE0040 is hidden diagnostic. there is no visual cue to users at all on where the diagnostics are (no error list entry, no squiggle). 
since there is no squiggle, there is no quick info by its own. in other words, this diagnostic can (or supposed to) only be fixed by LB at the left adornment. 

but @tmat have hit a design issue in this hidden diagnostic mechanism. 
editor's quick info will merge all squiggles intersecting each others and show its quick info and LB. 
for this case, since diagnostic is hidden, there is no squiggle hence no quick info for the diagnostic, but LB for the hidden diagnostic gets picked up. so it ends up show quick info from rude edit and LB from hidden diagnostic making this confusion since 2 shown are unrelated each other and there is nothing to let people know the LB is for another issue.

I can think of 4 possible fix? welcome any other idea.

1. leave it as it is. (LB showing up in quick info without any message related to it. making it worse, quick info WILL have message that has nothing to do with LB otherwise, quick info won't be there at the first place)
2. make sure quick info LB doesn't show any fix for hidden diagnostics. (less confusion since if there is LB, there will be a message related to that LB in quick info)
3. forbid this kind of hidden diagnostics/fixer. all diagnostic must have some kind of visual cue such as "...", squiggle, unnecessary adornment or something else. otherwise, it must be refactoring.
4. make quick info to show hidden diagnostics message as well.

my preference is 2 > 1 > 3 > 4

**Comment by CyrusNajmabadi** [comment]
I woudl be ok with a change to quick info for hidden diagnostics.  given that sort of approach, the title should probably not be "Code fixes shouldn't be offered for rude edits".  rather, it should be something like "Quick info should not tell me about fixes that are available for hidden diagnostics".

Users will still see the lightbulb on the left. But hovering over the squiggle will only show the info about that actual error.

**Comment by tmat** [comment]
> Users will still see the lightbulb on the left. But hovering over the squiggle will only show the info about that actual error.

:+1:

**Comment by tmat** [comment]
Decided that IDE features should not take rude edits into consideration. All features should be available regardless of debugging/Hot Reload status.
