### ISSUE TITLE
Roslyn Syntax Visualizer is not working in VS 2017 15.7.0 and 15.7.1

### ISSUE THREAD

**Issue by eriawan** [dotnet/roslyn#26792]
**Version Used**: 

15.7.0 and 15.7.1 (I have both)

**Steps to Reproduce**:

1. Install .NET Compiler Plarform SDK either from VS Marketplace of within VS 2017
2. Restart VS

**Expected Behavior**:

Syntax Visualizer works

**Actual Behavior**:

.NET Compiler Platform SDK is disabled because it's not compatible with VS 2017 15.7.0 and 15.7.1.

Screenshot:

![image](https://user-images.githubusercontent.com/8773147/39919297-5633d01a-553d-11e8-9e6b-7b53ede273c1.png)

**Comment by mikkelbu** [comment]
On my machine I have the syntax visualizer working on VS 15.7.1 even though the .NET Compiler Platform SDK is disabled, but I guess that installed the SDK before updating my VS.

**Comment by MaStr11** [comment]
The SDK is no longer distributed via the marketplace. It is part of the VS installer now. See the instructions at [docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/syntax-visualizer](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/syntax-visualizer) for details how to obtain it.

**Comment by MaStr11** [comment]
Related 
#25744 
#26094 
dotnet/roslyn-sdk#114

**Comment by sharwell** [comment]
Duplicate of #26094

**Comment by sharwell** [comment]
@jinujoseph @kuhlenh This is an ongoing problem :arrow_up:

**Comment by eriawan** [comment]
@MaStr11 

> The SDK is no longer distributed via the marketplace. It is part of the VS installer now. 

The the docs page should be updated to clarify this, and the VS marketplace should be updated as well.

**Comment by MaStr11** [comment]
@eriawan I second this. This is a known issue since VS 15.5 from December 2017 (see #23579). It was mentioned numerous times since then and has caused many questions as yours here or on gitter. Time will tell if this gets ever fixed (along with all the other outdated sections in the wiki). The problem is that the wiki entry and the marketplace description can only be fixed by the Roslyn team itself.

**Comment by eriawan** [comment]
@jmarolf 

Is there any progress on updating or clarifying this on MS Docs site? 
As far as I know, this issue is still relevant, because there's no clear information yet on obtaining Roslyn Syntax Visualizer.
Therefore, could we reopen this issue?

**Comment by jmarolf** [comment]
@eriawan we have docs about this [here](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/#install-using-the-workloads-view) but I am still tracking a way to make this less painful here https://github.com/dotnet/roslyn-sdk/issues/114
