### ISSUE TITLE
Tests not running on latest VS

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/roslyn#40267]
When i try, they just crash with:

```
Log level is set to Informational (Default).
Test data store opened in 63.006 sec.
StreamJsonRpc.RemoteInvocationException: The following TestContainer was not found 'C:\github\roslyn\artifacts\bin\Microsoft.CodeAnalysis.UnitTests\Debug\net472\Microsoft.CodeAnalysis.UnitTests.dll'
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__96`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Host.TestStoreHandler.<AddSourceBasedTestsAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Extensibility.ILoggerExtensions.<CallWithCatchAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
[12/9/2019 4:18:36.190 PM] ---------- Discovery started ----------
```

Note: in the past i've been told i can fix this by deleting the .vs folder.  But this is *not* a real solution.  It's a workaround for the product either storing bogus data, or not being able to handle the state of the world and the cached data being out of sync.  Such resilience must be designed in, and users should not have to fixup busted features because they were written haphazardly.

**Comment by CyrusNajmabadi** [comment]
Tagging @jinujoseph .  Note: i cannot report issues using "report a problem".  Can you direct as appropriate.  Note, i'm on hte latest preview:

![image](https://user-images.githubusercontent.com/4564579/70484232-09385e00-1aa0-11ea-89de-cd8c235f48b2.png)

**Comment by jinujoseph** [comment]
@shyamnamboodiripad

**Comment by shyamnamboodiripad** [comment]
Hi @CyrusNajmabadi Sorry you are running into this.

The stack trace posted above appears to be a red herring (i.e. this is a different bug we already have an internal fix for that is being tested - and this bug should not prevent tests from being executed).

Are you seeing anything else in the log after the `---- Discovery started ----` message or does the log end there? What happens if you try to execute the same test(s) a second time? We recently also fixed some issues where tests were being executed but the result would not be reflected in the test window. Are you seeing messages in the output log that indicate that the tests are in fact being executed?

Also wanted to double check that you are not running into this issue which several folks have reported running into recently after upgrading VS https://developercommunity.visualstudio.com/content/problem/834814/testhost-net-error.html.

(BTW, why are you unable to report this using "report a problem"? 😄 Since we are not regularly monitoring the Roslyn repo, I'll create an internal workitem to track this report. We can definitely have the conversation and debug the problem here - but if you were to use "report a problem" the broader community of VS preview users who may be running into the same issue may have better luck finding the report and our responses.)

Thanks for reporting and hope we can identify the root cause soon.

**Comment by CyrusNajmabadi** [comment]
> (BTW, why are you unable to report this using "report a problem"?

Because i get this:

![image](https://user-images.githubusercontent.com/4564579/70488008-152a1d00-1aac-11ea-947f-dcea62c76374.png)

Note that i've brought this up many times in the past, but have not seen improvements with this tool in a *loooong* time.

**Comment by CyrusNajmabadi** [comment]
> Are you seeing anything else in the log after the ---- Discovery started ---- message or does the log end there?

That is the entirety of the log.

**Comment by CyrusNajmabadi** [comment]
> What happens if you try to execute the same test(s) a second time?

I can't execute again because VS thinks the tests are currently executing.  i.e.

![image](https://user-images.githubusercontent.com/4564579/70488160-a7322580-1aac-11ea-8264-ee4c5bc9e276.png)

**Comment by shyamnamboodiripad** [comment]
> Note that i've brought this up many times in the past, but have not seen improvements with this tool in a loooong time.

Ack 😞 That's a bummer...

**Comment by shyamnamboodiripad** [comment]
> That is the entirety of the log.
> I can't execute again because VS thinks the tests are currently executing.

That's interesting. The last line of the output log indicates that `Discovery` is in progress. However the state of the test window UI indicates that tests are currently `Running`. I wonder if this is some sort of deadlock / hang.

Is the UI responsive? If yes, if you click on the red `Stop` button does that fix things? Are you able to run the test again after that?

**Comment by shyamnamboodiripad** [comment]
@CyrusNajmabadi If the UI is not responsive, it would be great if you could share a process dump...

**Comment by CyrusNajmabadi** [comment]
try

https://drive.google.com/file/d/1YiedU3xqZWq3dnhU4wh1C5PwTrRsAy3Z/view?usp=sharing  or
https://drive.google.com/file/d/1yHCJKTtsbO8ShKag714lUe18jgz-a2XZ/view?usp=sharing

**Comment by shyamnamboodiripad** [comment]
I don't think I am seeing anything in the dumps to confirm the UI hang theory. Was the UI unresponsive at the point where you collected the dumps?

**hang.dmp:** I'm not seeing TestWindow on any of the stacks. I am seeing editor and project system on the main thread. Looks like its processing a document save -
```
 	ntdll.dll!_ZwWaitForSingleObject@12() Line 129	Unknown
>	KERNELBASE.dll!WaitForSingleObjectEx(void * hHandle, unsigned long dwMilliseconds, int bAlertable) Line 1328	C
 	Microsoft.VisualStudio.Threading.ni.dll!59767115()	Unknown
 	Microsoft.VisualStudio.Threading.ni.dll![Frames below may be incorrect and/or missing, native debugger attempting to walk managed call stack]	Unknown
 	Microsoft.VisualStudio.Threading.ni.dll!59767100()	Unknown
 	[Managed to Native Transition]	
 	Microsoft.VisualStudio.Threading.dll!Microsoft.VisualStudio.Threading.NoMessagePumpSyncContext.Wait(System.IntPtr[] waitHandles, bool waitAll, int millisecondsTimeout) Line 64	C#
 	mscorlib.dll!System.Threading.SynchronizationContext.InvokeWaitMethodHelper(System.Threading.SynchronizationContext syncContext, System.IntPtr[] waitHandles, bool waitAll, int millisecondsTimeout) Line 349	C#
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	mscorlib.dll!System.Threading.Monitor.Wait(object obj, int millisecondsTimeout, bool exitContext) Line 203	C#
...
 	mscorlib.dll!System.Threading.Tasks.Task.Wait(System.TimeSpan timeout) Line 3083	C#
 	[Waiting on Async Operation, Open Tasks View in Parallel Stacks Window to view Async Call Stacks]	
 	Microsoft.VisualStudio.Threading.dll!Microsoft.VisualStudio.Threading.JoinableTaskFactory.WaitSynchronouslyCore(System.Threading.Tasks.Task task) Line 359	C#
 	Microsoft.VisualStudio.Threading.dll!Microsoft.VisualStudio.Threading.JoinableTaskFactory.WaitSynchronously(System.Threading.Tasks.Task task) Line 336	C#
 	Microsoft.VisualStudio.Threading.dll!Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread() Line 881	C#
 	Microsoft.VisualStudio.Threading.dll!Microsoft.VisualStudio.Threading.JoinableTask<bool>.CompleteOnCurrentThread() Line 85	C#
 	Microsoft.VisualStudio.Shell.UI.Internal.dll!Microsoft.VisualStudio.Services.FileChangeService.RunWithTracing<bool>(Microsoft.VisualStudio.Services.FileChangeService.CompletionTracer tracer, System.Func<System.Threading.CancellationToken, System.Threading.Tasks.Task<bool>> func) Line 1803	C#
 	Microsoft.VisualStudio.Shell.UI.Internal.dll!Microsoft.VisualStudio.Services.FileChangeService.RunWithTracing(Microsoft.VisualStudio.Services.FileChangeService.CompletionTracer tracer, System.Func<System.Threading.CancellationToken, System.Threading.Tasks.Task> func) Line 1792	C#
 	Microsoft.VisualStudio.Shell.UI.Internal.dll!Microsoft.VisualStudio.Services.FileChangeService.SyncFile(string filename) Line 864	C#
 	Microsoft.VisualStudio.Shell.UI.Internal.dll!Microsoft.VisualStudio.Services.FileChangeService.Microsoft.VisualStudio.Shell.Interop.IVsFileChangeEx.SyncFile(string filename) Line 494	C#
 	Microsoft.VisualStudio.Editor.Implementation.dll!Microsoft.VisualStudio.Editor.Implementation.TextDocData.SuspendFileChangeNotification(string pszFilename, int fSuspend) Line 724	C#
 	Microsoft.VisualStudio.Editor.Implementation.dll!Microsoft.VisualStudio.Editor.Implementation.TextDocData.BaseSave(string pszFilename, int fRemember) Line 794	C#
 	Microsoft.VisualStudio.Editor.Implementation.dll!Microsoft.VisualStudio.Editor.Implementation.TextDocData.Save(string pszFilename, int fRemember, uint nFormatIndex) Line 678	C#
 	Microsoft.VisualStudio.Editor.Implementation.dll!Microsoft.VisualStudio.Editor.Implementation.TextDocData.Save(string pszFileName, int fRemember) Line 866	C#
 	[Native to Managed Transition]	
 	msenv.dll!HrSaveToFile(int fNoSaveAs, IPersistFileFormat * pPersistFileFmt, IPersistFile * pPersistFile, const wchar_t * lpstrPath, wchar_t * * pbstrDocNew, int * pfCanceled) Line 90	C++
 	msenv.dll!HrSaveDocDataToFile(__VSSAVEFLAGS grfSave, IUnknown * punkPersistFile, const wchar_t * lpstrUntitledPath, wchar_t * * pbstrDocNew, int * pfCanceled) Line 282	C++
 	msenv.dll!CVsUIShell::SaveDocDataToFile(__VSSAVEFLAGS grfSave, IUnknown * punkPersistFile, const wchar_t * lpstrUntitledPath, wchar_t * * pbstrDocumentNew, int * pfCanceled) Line 3206	C++
 	[Managed to Native Transition]	
 	Microsoft.VisualStudio.Editor.Implementation.dll!Microsoft.VisualStudio.Editor.Implementation.TextDocData.SaveDocData(Microsoft.VisualStudio.Shell.Interop.VSSAVEFLAGS dwSave, out string pbstrMkDocumentNew, out int pfSaveCanceled) Line 345	C#
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.SaveItem.AnonymousMethod__0(Microsoft.Internal.VisualStudio.Shell.TelemetryActivity _) Line 2278	C#
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.HrMutate.AnonymousMethod__0() Line 3992	C#
 	Microsoft.VisualStudio.Threading.dll!Microsoft.VisualStudio.Threading.JoinableTaskFactory.ExecuteJob<Microsoft.VisualStudio.ProjectSystem.VS.HResult>(System.Func<System.Threading.Tasks.Task> asyncMethod, Microsoft.VisualStudio.Threading.JoinableTask job) Line 703	C#
 	Microsoft.VisualStudio.Threading.dll!Microsoft.VisualStudio.Threading.JoinableTaskFactory.RunAsync<Microsoft.VisualStudio.ProjectSystem.VS.HResult>(System.Func<System.Threading.Tasks.Task<Microsoft.VisualStudio.ProjectSystem.VS.HResult>> asyncMethod, bool synchronouslyBlocking, Microsoft.VisualStudio.Threading.JoinableTaskCreationOptions creationOptions) Line 692	C#
 	Microsoft.VisualStudio.Threading.dll!Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run<Microsoft.VisualStudio.ProjectSystem.VS.HResult>(System.Func<System.Threading.Tasks.Task<Microsoft.VisualStudio.ProjectSystem.VS.HResult>> asyncMethod, Microsoft.VisualStudio.Threading.JoinableTaskCreationOptions creationOptions) Line 507	C#
 	Microsoft.VisualStudio.ProjectSystem.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.ExecuteSynchronously<Microsoft.VisualStudio.ProjectSystem.VS.HResult>(System.Func<System.Threading.Tasks.Task<Microsoft.VisualStudio.ProjectSystem.VS.HResult>> asyncAction) Line 137	C#
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.HrInvoke.AnonymousMethod__0() Line 3889	C#
 	Microsoft.VisualStudio.ProjectSystem.VS.dll!Microsoft.VisualStudio.ProjectSystem.VS.HResult.Invoke(System.Func<Microsoft.VisualStudio.ProjectSystem.VS.HResult> action, System.IServiceProvider vsShellServiceProvider, Microsoft.VisualStudio.ProjectSystem.IProjectFaultHandlerService projectFaultHandlerService, Microsoft.VisualStudio.ProjectSystem.UnconfiguredProject project) Line 324	C#
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.HrInvoke(System.Func<System.Threading.Tasks.Task<Microsoft.VisualStudio.ProjectSystem.VS.HResult>> asyncAction, bool registerProjectFaultHandlerService) Line 3888	C#
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.HrMutate(System.Func<Microsoft.Internal.VisualStudio.Shell.TelemetryActivity, System.Threading.Tasks.Task<Microsoft.VisualStudio.ProjectSystem.VS.HResult>> asyncAction, bool includesFileSystemChange, bool registerProjectFaultHandlerService, string telemetryActivity) Line 3980	C#
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.SaveItem(Microsoft.VisualStudio.Shell.Interop.VSSAVEFLAGS saveFlag, string silentSaveAsName, uint itemid, System.IntPtr docData, out int cancelledParam) Line 2206	C#
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNodeWrapper.SaveItem(Microsoft.VisualStudio.Shell.Interop.VSSAVEFLAGS dwSave, string pszSilentSaveAsName, uint itemid, System.IntPtr punkDocData, out int pfCanceled) Line 623	C#
 	[Native to Managed Transition]	
 	msenv.dll!CSaveTreeItem::HrSave(CSaveTree * pST) Line 676	C++
 	msenv.dll!CSaveTreeItem::HrSave(CSaveTree * pST) Line 587	C++
 	msenv.dll!CSaveTree::SaveChanges() Line 1140	C++
 	msenv.dll!CSaveTree::PromptSaveChanges() Line 1235	C++
...
```

**devenv-hang.dmp:** There is one TestWindow thread that is trying to update its VS commands enabled / disabled status after being notified about some UIContext change in VS. This thread is blocked inside JTF.Run trying to jump on the UI thread. UI thread is processing a document close -
```
 	ntdll.dll!_ZwWaitForSingleObject@12() Line 129	Unknown
>	KERNELBASE.dll!WaitForSingleObjectEx(void * hHandle, unsigned long dwMilliseconds, int bAlertable) Line 1328	C
 	Microsoft.VisualStudio.Threading.ni.dll!59cc7115()	Unknown
 	Microsoft.VisualStudio.Threading.ni.dll![Frames below may be incorrect and/or missing, native debugger attempting to walk managed call stack]	Unknown
 	Microsoft.VisualStudio.Threading.ni.dll!59cc7100()	Unknown
 	[Managed to Native Transition]	
 	Microsoft.VisualStudio.Threading.dll!Microsoft.VisualStudio.Threading.NoMessagePumpSyncContext.Wait(System.IntPtr[] waitHandles, bool waitAll, int millisecondsTimeout) Line 64	C#
 	mscorlib.dll!System.Threading.SynchronizationContext.InvokeWaitMethodHelper(System.Threading.SynchronizationContext syncContext, System.IntPtr[] waitHandles, bool waitAll, int millisecondsTimeout) Line 349	C#
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	mscorlib.dll!System.Threading.Monitor.Wait(object obj, int millisecondsTimeout, bool exitContext) Line 203	C#
 	mscorlib.dll!System.Threading.Monitor.Wait(object obj, int millisecondsTimeout) Line 213	C#
...
 	mscorlib.dll!System.Threading.Tasks.Task.Wait(System.TimeSpan timeout) Line 3083	C#
 	[Waiting on Async Operation, Open Tasks View in Parallel Stacks Window to view Async Call Stacks]	
 	Microsoft.VisualStudio.Threading.dll!Microsoft.VisualStudio.Threading.JoinableTaskFactory.WaitSynchronouslyCore(System.Threading.Tasks.Task task) Line 359	C#
 	Microsoft.VisualStudio.Threading.dll!Microsoft.VisualStudio.Threading.JoinableTaskFactory.WaitSynchronously(System.Threading.Tasks.Task task) Line 336	C#
 	Microsoft.VisualStudio.Threading.dll!Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread() Line 881	C#
 	Microsoft.VisualStudio.Threading.dll!Microsoft.VisualStudio.Threading.JoinableTask<System.__Canon>.CompleteOnCurrentThread() Line 84	C#
 	Microsoft.VisualStudio.Threading.dll!Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run<string>(System.Func<System.Threading.Tasks.Task<string>> asyncMethod, Microsoft.VisualStudio.Threading.JoinableTaskCreationOptions creationOptions) Line 508	C#
 	Microsoft.VisualStudio.Threading.dll!Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run<string>(System.Func<System.Threading.Tasks.Task<string>> asyncMethod) Line 488	C#
 	Microsoft.VisualStudio.Shell.UI.Internal.dll!Microsoft.VisualStudio.Services.FileChangeService.RunWithTracing<string>(Microsoft.VisualStudio.Services.FileChangeService.CompletionTracer tracer, System.Func<System.Threading.CancellationToken, System.Threading.Tasks.Task<string>> func) Line 1803	C#
 	Microsoft.VisualStudio.Shell.UI.Internal.dll!Microsoft.VisualStudio.Services.FileChangeService.UnadviseFileChange(uint cookie) Line 734	C#
 	Microsoft.VisualStudio.Shell.UI.Internal.dll!Microsoft.VisualStudio.Services.FileChangeService.Microsoft.VisualStudio.Shell.Interop.IVsFileChangeEx.UnadviseFileChange(uint cookie) Line 471	C#
 	Microsoft.VisualStudio.Editor.Implementation.dll!Microsoft.VisualStudio.Editor.Implementation.TextDocData.SetFileChangeNotification(string pszFileName, bool addNotification) Line 702	C#
 	Microsoft.VisualStudio.Editor.Implementation.dll!Microsoft.VisualStudio.Editor.Implementation.TextDocData.Close() Line 125	C#
 	[Native to Managed Transition]	
 	msenv.dll!CRunningDocInfo::CloseDocData() Line 408	C++
 	msenv.dll!CRunningDocInfo::~CRunningDocInfo() Line 390	C++
 	msenv.dll!CRunningDocInfo::Unlock(unsigned long dwRDTLockType) Line 1280	C++
 	msenv.dll!CRunningDocTable::Impl::UnlockDocument(unsigned long dwRDTLockType, unsigned long dwCookie) Line 800	C++
 	msenv.dll!CRunningDocTable::UnlockDocument::__l8::<lambda>() Line 777	C++
 	msenv.dll!FreeThreadingHelpers::UIThreadSynchronizedFunc<HRESULT <lambda>(void)>(CRunningDocTable::UnlockDocument::__l8::HRESULT <lambda>(void) func, const wchar_t * pCallingFunction) Line 18	C++
 	msenv.dll!FreeThreadingHelpers::UIThreadSynchronizedFunc<HRESULT <lambda>(void)>(CRunningDocTable::UnlockDocument::__l8::HRESULT <lambda>(void) func, const char *) Line 95	C++
 	msenv.dll!CRunningDocTable::UnlockDocument(unsigned long dwRDTLockType, unsigned long dwCookie) Line 777	C++
 	[Inline Frame] msenv.dll!CRunningDocLock::Unlock() Line 368	C++
 	[Inline Frame] msenv.dll!CRunningDocLock::{dtor}() Line 374	C++
 	msenv.dll!HrCloseItem(unsigned long docCookie) Line 1845	C++
 	msenv.dll!CRunningDocTable::Impl::CloseDocuments(unsigned long grfSaveOptions, IVsHierarchy * pHierarchy, unsigned long docCookie) Line 2891	C++
 	msenv.dll!CRunningDocTable::CloseDocuments::__l17::<lambda>() Line 2835	C++
 	msenv.dll!FreeThreadingHelpers::UIThreadSynchronizedFunc<HRESULT <lambda>(void)>(CRunningDocTable::CloseDocuments::__l17::HRESULT <lambda>(void) func, const wchar_t * pCallingFunction) Line 18	C++
 	[Inline Frame] msenv.dll!FreeThreadingHelpers::UIThreadSynchronizedFunc(CRunningDocTable::CloseDocuments::__l17::HRESULT <lambda>(void)) Line 95	C++
 	msenv.dll!CRunningDocTable::CloseDocuments(unsigned long grfSaveOptions, IVsHierarchy * pHierarchy, unsigned long docCookie) Line 2835	C++
 	[Managed to Native Transition]	
 	Microsoft.VisualStudio.Shell.15.0.dll!Microsoft.VisualStudio.Shell.RunningDocumentTable.CloseDocuments(Microsoft.VisualStudio.Shell.Interop.__FRAMECLOSE options, Microsoft.VisualStudio.Shell.Interop.IVsHierarchy hierarchy, uint docCookie) Line 262	C#
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.DocumentManager.Close(Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.SimpleHierarchyNode projectItem, Microsoft.VisualStudio.Shell.Interop.__FRAMECLOSE closeFlag) Line 174	C#
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.DocumentManager.CloseOrDetachDocument(Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.SimpleHierarchyNode projectItem) Line 229	C#
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.SimpleItemNode.CloseOrDetachDocument() Line 389	C#
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.SimpleItemNode.CloseOrDetachDocument() Line 362	C#
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.TreeService.TreeData.OnBeforeApplyTree() Line 1295	C#
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.TreeService.ApplyAsync(Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.TreeService.TreeData value) Line 594	C#
...
```

**Comment by shyamnamboodiripad** [comment]
@CyrusNajmabadi After digging a bit more looks like we did recently fix a hang that was related to the TestWindow thread stack the 2nd dump (devenv-hang.dmp) (i.e. the code path in that stack is no longer invoked in latest internal builds after we fixed that hang). However, based on the stacks I don't think this dump is the hang that we fixed...

I'd still be interested to know whether the VS UI was completely unresponsive for both dumps above and whether you are able to repro the issue consistently (i.e. whether this was a one off hang v/s you are completely blocked from running tests for Roslyn.sln on 16.5 P1). Thanks!

**Comment by shyamnamboodiripad** [comment]
Also tagging @Cosifne who is investigating another (seemingly unrelated) hang in 16.3 just in case there is any link between the two issues.

**Comment by Jetski5822** [comment]
I know this is an old thread; but im still seeing alot of these errors on VS2022

```
07/12/2021 11:07:45.212 AM] StreamJsonRpc.RemoteInvocationException: Failed to perform operation, the store is closed.
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__139`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.TestWindow.Client.ClientSession.<>c__DisplayClass73_0.<<DiscoverTestsAsync>b__0>d.MoveNext()
```

Either the Store is closed, or the connection is lost... the VS Test window spins but doesnt do anything.
