### ISSUE TITLE
VS2019 suggested switch expression while preview not enabled

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#41825]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/919574/vs2019-suggested-switch-expression-while-preview-n.html)._

---
I'm using a switch statement on an int value to return a bool. It looks something like:

```c#
switch (value)
{
    case 0:
        return ...;
    case 1:
        return ...;
    case 2:
        return ...;
    default:
        return false;
}
```

VS suggests `IDE0066 Use 'switch' expression`, which turns this block into:

```c#
return value switch
{
    0 => ...,
    1 => ...,
    2 => ...,
    _ => false,
};
```

Building then gives me `error CS8652: The feature 'recursive patterns' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version.`

Since I do not have the preview enabled, maybe VS shouldn't suggest the feature?

---
#### Visual Studio Feedback System on 2/17/2020, 02:15 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by allisonchou** [comment]
I believe this error is actually under compilers, based on the error code and that the user is having problems at build. (If I'm wrong here, someone feel free to correct me.)

Additionally, I was unable to repro the issue, so it's possible it may have been fixed, but further verification is probably needed.

**Comment by jaredpar** [comment]
@allisonchou 

The issue here is about the suggestion to use the new `switch` expression feature. That suggestion is controlled by the IDE. In this specific case the resulting code is illegal and the compiler correctly raises an error. The IDE can do one of two things here:

1. Not offer the suggestion when the feature is not supported by the language version
1. Unconditionally offer the suggestion.

I believe the IDE has deliberately decided on (2) here. @jasonmalinowski can confirm.

**Comment by Zannick** [comment]
Filing user here, confirming it still reproduces in VS2019 16.7.1 and including my versions below in case further verification is needed.

<details>
<summary>Versions</summary>

```
Microsoft Visual Studio Community 2019 Version 16.7.1
VisualStudio.16.Release/16.7.1+30406.217
Microsoft .NET Framework Version 4.8.04084
Installed Version: Community

ASP.NET and Web Tools 2019   16.7.532.28833
ASP.NET Core Razor Language Services   16.1.0.2035807+72d099b977d3a85e65fa3b0614ca8cfc803fef02
ASP.NET Web Frameworks and Tools 2019   16.7.532.28833
Azure App Service Tools v3.0.0   16.7.532.28833
Azure Functions and Web Jobs Tools   16.7.532.28833
C# Tools   3.7.0-6.20375.2+34202cc2f3e869fd70a26d8237f4552cf9e192cf
Common Azure Tools   1.10
CreateActionClasses Extension   1.0
IntelliCode Extension   1.0
```
</details>

**Comment by Zannick** [comment]
I have just had this happen with another feature: `coalescing assignment`. As jaredpar said, the IDE should not offer the suggestion when the feature is not supported by the language version.

**Comment by CyrusNajmabadi** [comment]
@Zannick please file an issue on that so we can resolve it.  thanks :)

**Comment by Zannick** [comment]
I figured it's the same underlying issue here, of suggestions not taking into account the language version. If you're sure, though, I'll file a separate issue for that.

**Comment by CyrusNajmabadi** [comment]
It's not the same underlying issue :)   Each feature is separate and would need their own fixes to address the problem.  For example, i'm surrpised you're having an issue with Compound-Coalesce as we have an explicit version check in it here:

https://github.com/dotnet/roslyn/blob/eb0581d3b8df8ac819c092eb026b273fe74c1b54/src/Analyzers/Core/Analyzers/UseCompoundAssignment/AbstractUseCompoundAssignmentDiagnosticAnalyzer.cs#L83-L87

https://github.com/dotnet/roslyn/blob/eb0581d3b8df8ac819c092eb026b273fe74c1b54/src/Analyzers/CSharp/Analyzers/UseCompoundAssignment/CSharpUseCompoundAssignmentDiagnosticAnalyzer.cs#L26-L28

So if you are running into an issue, someone will have to investigate it.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/dotnet/roslyn/pull/54253.
