### ISSUE TITLE
Serialize document states without loading text

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslyn#43802]
**Version Used**: 16.6 Preview 3

Currently `DocumentStateChecksums` loads the text of documents here:

https://github.com/dotnet/roslyn/blob/1b17eae2aaa77c8c5f057dc657fc2a9d93fadb59/src/Workspaces/Core/Portable/Workspace/Solution/StateChecksums.cs#L239

This operation can load a large number of documents into a dictionary which are not all in use at the same time. This operation should instead place a _recoverable_ text in the dictionary, which can be loaded on demand at a point where it is needed.

🔗 This is the root cause of https://developercommunity.visualstudio.com/content/problem/1008598/vs-2019-constantly-crashing-because-of-addition-of.html

**Comment by tmat** [comment]
I'm not sure I understand. We put the text to the results map only when the text is requested by the ServiceHub process. So we will serialize the text to OOP.

**Comment by sharwell** [comment]
@tmat The problem occurs when OOP requests many text documents at once - 1300+ in the linked issue. All of the text was loaded before serialization started, leading to an OOM before any of the documents were released.

**Comment by tmat** [comment]
I see. Maybe the better approach would be to restructure the asset retrieval code then. Instead of first adding it to a map and then serializing the map we could just serialize assets as we traverse them.

**Comment by tmat** [comment]
That said such approach might still OOM in low memory cases when we can't fit the serialized versions of the data in memory. So, perhaps we could use a different technique for potentially large data - the same that we are using for metadata references. Send them to OOP via virtual memory. So the serialized version of a text document would only be an index to virtual memory storage.

**Comment by JayCroghan** [comment]
16.4.8 R3 does not fix this issue - I installed it today and opened the massive project and within seconds I get OOM.

**Comment by sharwell** [comment]
@JayCroghan Visual Studio 16.8 Preview 3 and newer fixes this issue (the code which led to this does not exist anymore). However, there may be other problems present. If you file a feedback using the following steps we can start the investigation:
https://docs.microsoft.com/en-us/visualstudio/ide/how-to-increase-chances-of-performance-issue-being-fixed?view=vs-2019#crashes

**Comment by JayCroghan** [comment]
> @JayCroghan Visual Studio 16.8 Preview 3 and newer fixes this issue (the code which led to this does not exist anymore). However, there may be other problems present. If you file a feedback using the following steps we can start the investigation

I did that, attached my crash dumps and logs and after 2 weeks it was closed a duplicate of this issue...

**Comment by sharwell** [comment]
@JayCroghan Thanks for the update. It appears there has been a mistake in the milestone marker. I can see the faulty line in the code that shipped in 16.8 Preview 3:

https://github.com/dotnet/roslyn/blob/Visual-Studio-2019-Version-16.8-Preview-3/src/Workspaces/Core/Portable/Workspace/Solution/StateChecksums.cs#L239

However, the code is fixed for more recent 16.8 previews. I'm still trying to determine if the fix is first in 16.8 Preview 4 or 16.8 Preview 5.

**Comment by JayCroghan** [comment]
@sharwell Well, that makes me feel a hell of a lot more sane, so it's _almost_ a relief this isn't fixed yet!

**Comment by JayCroghan** [comment]
@sharwell @jinujoseph so we are up to 16.8 P6, can you confirm this has been released yet? Our entire development team have to deal with constant crashes when opening the solution for the first time until they can successfully unload all of the tests. It's causing a lot of downtime. Thanks.

**Comment by sharwell** [comment]
@JayCroghan yes it would be fixed there. If you are seeing crashes, we would need a new report to review.

**Comment by JayCroghan** [comment]
@sharwell do you ever sleep :) ? I haven't tried since, updating my preview machine right now and I'll raise another bug if it's still crashing thanks.
