### ISSUE TITLE
Impossible to upload Roslyn Analyzer vsix to VS Gallery

### ISSUE THREAD

**Issue by bkoelman** [dotnet/roslyn#4459]
Upload fails with message:

```You can only upload template VSIX files for the Visual Studio Express SKUs.```

Repro steps:
1. Create a new analyzer in VS2015 RTM
2. Make release build
3. Go to [visualstudiogallery.msdn.microsoft.com](visualstudiogallery.msdn.microsoft.com) and try to upload the .vsix from bin\Release.

This is what the default analyzer project template generates.

```xml
<PackageManifest Version="2.0.0" xmlns="http://schemas.microsoft.com/developer/vsx-schema/2011">
  <Metadata>
    ..............
  </Metadata>
  <Installation>
    <InstallationTarget Version="[14.0,]" Id="Microsoft.VisualStudio.Pro" />
    <InstallationTarget Version="[14.0,]" Id="Microsoft.VisualStudio.VSWinDesktopExpress" />
    <InstallationTarget Version="[14.0,]" Id="Microsoft.VisualStudio.VWDExpress" />
    <InstallationTarget Version="[14.0,]" Id="Microsoft.VisualStudio.VSWinExpress" />
  </Installation>
  <Dependencies>
    <Dependency Id="Microsoft.Framework.NDP" DisplayName="Microsoft .NET Framework" Version="[4.5.2,)" />
  </Dependencies>
  <Assets>
    <Asset Type="Microsoft.VisualStudio.MefComponent" Path="MyAnalyzer.dll" />
    <Asset Type="Microsoft.VisualStudio.Analyzer" Path="MyAnalyzer.dll" />
  </Assets>
</PackageManifest>
```

What should be changed to make upload possible?

**Comment by bkoelman** [comment]
I found an answer at https://social.msdn.microsoft.com/Forums/vstudio/en-US/349f0f5f-9e85-4fcf-8709-0a8ce4fa58e8/how-to-develop-vs-2015-extension-that-will-work-with-all-editions-of-vs?forum=vsx.

After changing the extension.vsixmanifest like this:

```xml
<Installation>
    <InstallationTarget Version="[14.0,]" Id="Microsoft.VisualStudio.Pro" />
  </Installation>
```
it installs and runs fine in Community Edition 2015. I have not tested with Pro/Enterprise. But it looks like the Analyzer project template needs to be updated to this for Gallery uploads to succeed out-of-the-box.

**Comment by jmarolf** [comment]
This has been fixed internally.  I'll reply back here when I can give you a VSIX to test.

**Comment by bkoelman** [comment]
Just tried to create a new blank analyzer project. Its .vsixmanifest still contains these 4 installation targets. Where will the fix become visible?

**Comment by jmarolf** [comment]
We have not yet published the SDK for update 1.  As soon as that's available, you should see the fix.

**Comment by bkoelman** [comment]
Just tried with VS2015 Update 1 RTM. I'm still not seeing the fix.

**Comment by jmarolf** [comment]
I have not yet published the update 1  SDK, waiting on a nuget fix

**Comment by jmarolf** [comment]
@bkoelman I update the Roslyn SDk, this should be fixed now

**Comment by bkoelman** [comment]
@jmarolf Fix confirmed. Looks great. Thanks for letting me know.

**Comment by bkoelman** [comment]
@jmarolf I was getting into the same versioning issue as @ProductiveRage mentioned in https://github.com/dotnet/roslyn/issues/4831#issuecomment-164719892. Just like him, I was able to downgrade versions so my analyzer builds and runs in both VS2015 RTM and Update1.

So this got me thinking. Wouldn't it be better if the newer project templates would still reference the old package versions (except for Microsoft.CodeAnalysis.Analyzers 1.1.0, see https://github.com/dotnet/roslyn/issues/7276), such as Immutable v1.36 etc. and without the binding redirects? Update1 has binding redirects for 1.36 to 1.37, so it uses the new assembly. RTM has 1.36, so no binding redirects and will use 1.36.

That way, analyzers can be built and deployed in RTM and Update1 without issues. Right now I would not recommend anyone to create an analyzer with the updated SDK, as it breaks the RTM scenario.

**Comment by jmarolf** [comment]
@bkoelman I agree, I'll prepare a fix today
