### ISSUE TITLE
Performing a whole solution analysis in VS2019

### ISSUE THREAD

**Issue by pavanupb** [dotnet/roslyn#45610]
I am developing an analyzer where I need to report diagnostics from a list after compiling the entire solution in VS 2019. I registered a CompilationEndAction in my CompilationStartAction but the breakpoint at my CompilationEndAction is not getting hit. I have checked the "Enable full solution analysis" options in VS 2019. Is there a different way to enable full solution analysis?. I am trying to perform a taint analysis and adding tainted values to a list. I would like to report diagnostics for all the tainted values in the list after compiling the entire solution. Is there any other way apart from using the CompilationEndAction?

**Comment by mavasani** [comment]
> "Enable full solution analysis" options in VS 2019

Just to confirm - you have selected "Entire solution" for the radio buttons here: https://docs.microsoft.com/visualstudio/code-quality/configure-live-code-analysis-scope-managed-code?view=vs-2019#custom-analysis-scope

**Comment by pavanupb** [comment]
I am using VS 2019 community edition. I do not see the radio buttons as mentioned in : https://docs.microsoft.com/visualstudio/code-quality/configure-live-code-analysis-scope-managed-code?view=vs-2019#custom-analysis-scope.
I am able to see an option as shown below in my VS 2019
![CodeAnalysis](https://user-images.githubusercontent.com/38906373/86376588-7f442280-bc87-11ea-8fbc-c16cf17dc100.PNG)

**Comment by mavasani** [comment]
Which version of VS2019 are you using? Can you update to latest release or prerelease as per https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes or https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview?

**Comment by pavanupb** [comment]
I am currently using version 16.4.3

**Comment by pavanupb** [comment]
I installed the latest version. Now I am able to see the radio buttons. I activated it and I am still facing issues while reporting diagnostics when rebuilding the entire solution.
For instance, I have a program 

```
void abc()
{
     String test1 = "Hard Code String 1";
     String test2 = "Hard-Coded String 2";

     foo(test1, test2)
}

void foo(String value1, value2)
{
   String string1 = value1;
   String string2 = value2;
}
```
I am performing a taint analysis along with alias analysis, where my analyzer reports diagnostics for all tainted values. When I open each document individually I see the diagnostics being reported correctly. But when I rebuild the solution with "EntireSolution" radio button selected, I do not see all the diagnostics being reported.

**Comment by mavasani** [comment]
> I am performing a taint analysis along with alias analysis, where my analyzer reports diagnostics for all tainted values.

Just to confirm, you are reporting diagnostics with compilation end action correct?

> But when I rebuild the solution with the "EntireSolution" radio button selected, I do not see all the diagnostics being reported.

Are you suggesting that the command line build output does not report these diagnostics? Can you please provide details on each of the below actions:
1. Invoke a command line build outside of VS
2. Invoke a build command in VS and look at output window text
3. Invoke a build command in VS and look at error list

**Comment by mavasani** [comment]
> Method abc() is defined in one project and foo() is defined in another project. I am using the analysis data collected while analyzing abc() in method foo().

So, are you doing cross project/assembly analysis? Seems like your analyzer is crossing compilation/project boundaries, which means it cannot work reliably on build as each project is compiled separately on command line build - there is no concept of solution on command line, each project is compiled separately, with analyzer instances not being shared.

**Comment by pavanupb** [comment]
> > I am performing a taint analysis along with alias analysis, where my analyzer reports diagnostics for all tainted values.
> 
> Just to confirm, you are reporting diagnostics with compilation end action correct?
> 
> > But when I rebuild the solution with the "EntireSolution" radio button selected, I do not see all the diagnostics being reported.
> 
> Are you suggesting that the command line build output does not report these diagnostics? Can you please provide details on each of the below actions:
> 
> 1. Invoke a command line build outside of VS
> 2. Invoke a build command in VS and look at output window text
> 3. Invoke a build command in VS and look at error list

Right now I am not using the compilation end action as it is not getting executed. So I am reporting the diagnostics inline while analyzing the code. i.e, I am reporting the diagnostics in the registered syntax node actions. Since I am using a dictionary to store the context information, would that create a problem while performing analysis for the whole solution?.

Regarding points 2 and 3, I am able to see the same behavior. However, when I build the project for several times, I see at some point all the diagnostics being reported.

Regarding point 1 I haven't tried out since I am using VSIX installer and did not try installing the nugget package for the project.

**Comment by pavanupb** [comment]
> > Method abc() is defined in one project and foo() is defined in another project. I am using the analysis data collected while analyzing abc() in method foo().
> 
> So, are you doing cross project/assembly analysis? Seems like your analyzer is crossing compilation/project boundaries, which means it cannot work reliably on build as each project is compiled separately on command line build - there is no concept of solution on command line, each project is compiled separately, with analyzer instances not being shared.

Okay. I also tried within the same project. When I build my project in VS2019 with the analyze the whole solution option enabled, I see that some of the diagnostics are not getting reported. But when I open a particular document I am able to see the diagnostics getting reported correctly with the red/green squiggles.

**Comment by pavanupb** [comment]
I created a nuget package of my analyzer and tried to build it from the command line. I am getting the error : CSC : warning CS8032: An instance of the analyzer cannot be created. Exception has been thrown by the target of an invocation. I am using "Microsoft.CodeAnalysis.Analyzers" v2.6.2 and "Microsoft.CodeAnalysis.CSharp.Workspaces" v2.10. I went through several posts raised on the same issue, but could not solve the warning. Do you have any suggestions on the same?

I would like to know whether the analyzer starts the analysis from the file containing the main() function when I enable the analysis scope for the entire solution.

**Comment by pavanupb** [comment]
> > > I am performing a taint analysis along with alias analysis, where my analyzer reports diagnostics for all tainted values.
> > 
> > 
> > Just to confirm, you are reporting diagnostics with compilation end action correct?
> > > But when I rebuild the solution with the "EntireSolution" radio button selected, I do not see all the diagnostics being reported.
> > 
> > 
> > Are you suggesting that the command line build output does not report these diagnostics? Can you please provide details on each of the below actions:
> > 
> > 1. Invoke a command line build outside of VS
> > 2. Invoke a build command in VS and look at output window text
> > 3. Invoke a build command in VS and look at error list
> 
> Right now I am not using the compilation end action as it is not getting executed. So I am reporting the diagnostics inline while analyzing the code. i.e, I am reporting the diagnostics in the registered syntax node actions. Since I am using a dictionary to store the context information of other code blocks, would that create a problem while performing analysis for the whole solution?.
> 
> Regarding points 2 and 3, I am able to see the same behavior. However, when I build the project several times, I see at some point all the diagnostics being reported.
> 
> Regarding point 1, I haven't tried out since I am using the VSIX installer and did not try installing the nuget package for the project.

@mavasani Tried with CompilationEndAction. But still, I am observing the same behavior.  When I go to individual files I see all the diagnostics being reported correctly but when I build the project I don't see all the diagnostics being reported.

**Comment by mavasani** [comment]
>@mavasani Tried with CompilationEndAction. But still, I am observing the same behavior. When I go to individual files I see all the diagnostics being reported correctly but when I build the project I don't see all the diagnostics being reported.

@pavanupb Can you confirm if your analysis is not relying on any analysis results from outside the current compilation/project?

**Comment by mavasani** [comment]
> when I build the project I don't see all the diagnostics being reported.

Can you clarify if you mean build the project in VS or command line? If the former, are you looking at diagnostics in error list or output window?

**Comment by pavanupb** [comment]
> > when I build the project I don't see all the diagnostics being reported.
> 
> Can you clarify if you mean build the project in VS or command line? If the former, are you looking at diagnostics in error list or output window?

I am building the project in VS and I am looking at the error list window

**Comment by pavanupb** [comment]
> > @mavasani Tried with CompilationEndAction. But still, I am observing the same behavior. When I go to individual files I see all the diagnostics being reported correctly but when I build the project I don't see all the diagnostics being reported.
> 
> @pavanupb Can you confirm if your analysis is not relying on any analysis results from outside the current compilation/project?

I am not relying on any analysis result outside the current project/current compilation.

**Comment by mavasani** [comment]
> I am building the project in VS and I am looking at the error list window

Thanks. Can you check if the diagnostics are reported in the Output window? This does seem like a bug in VS IDE that should be fixed, just trying to figure out which part of the system needs the fix.

**Comment by sharwell** [comment]
> Microsoft.CodeAnalysis.CSharp.Workspaces

One potential problem is command line analyzers cannot use this assembly (directly or indirectly). The approach I recommend is replacing this package reference with Microsoft.CodeAnalysis.CSharp.Common instead. See https://github.com/microsoft/vs-threading/pull/440 for an example of how this dependency was removed in another project.

**Comment by pavanupb** [comment]
> > I am building the project in VS and I am looking at the error list window
> 
> Thanks. Can you check if the diagnostics are reported in the Output window? This does seem like a bug in VS IDE that should be fixed, just trying to figure out which part of the system needs the fix.

I see diagnostics are not being reported in the output window. Tried with changing the output verbosity to diagnostic in "Build and Run" section in Options

**Comment by pavanupb** [comment]
> > Microsoft.CodeAnalysis.CSharp.Workspaces
> 
> One potential problem is command line analyzers cannot use this assembly (directly or indirectly). The approach I recommend is replacing this package reference with Microsoft.CodeAnalysis.CSharp.Common instead. See [microsoft/vs-threading#440](https://github.com/microsoft/vs-threading/pull/440) for an example of how this dependency was removed in another project.

Tried replacing with Microsoft.CodeAnalysis.CSharp.Common, still facing the same issue. 

```
  <ItemGroup>
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="1.1.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="2.6.2" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="2.10.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.FlowAnalysis.Utilities" Version="2.9.6" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="3.1.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="3.1.0" />    
  </ItemGroup>
```

**Comment by mavasani** [comment]
> I see diagnostics are not being reported in the output window. 

Alright, so this indicates this is not a VS IDE bug. There is likely an issue with your analyzer not functioning as expected from non-IDE context. Very likely this is due to the reason @sharwell cited, your analyzer is eventually invoking into some assembly that is only available when executing analyzers within VS process (devenv.exe), but not outside it. Is it possible for you to share your analyzer sources and/or publish it to a github repo?

**Comment by pavanupb** [comment]
> > I see diagnostics are not being reported in the output window.
> 
> Alright, so this indicates this is not a VS IDE bug. There is likely an issue with your analyzer not functioning as expected from non-IDE context. Very likely this is due to the reason @sharwell cited, your analyzer is eventually invoking into some assembly that is only available when executing analyzers within VS process (devenv.exe), but not outside it. Is it possible for you to share your analyzer sources and/or publish it to a github repo?

@mavasani I have added you as the collaborator.

**Comment by mavasani** [comment]
@pavanupb Thanks. Looking at your code, it seems you rely on dependency injection model, which seems similar to MEF, which is unavailable in compiler layer for execution in explicit build invocations. I am suspecting none of the dependency injection logic is functioning, hence the issue. Can you try to adjust your analyzer to throw an exception at places where you expect dependency injection logic to kick in and succeed with non-empty results? If my guess is correct, you should see an AD0001 analyzer exception diagnostic in your build scenario, confirming this theory.

**Comment by pavanupb** [comment]
@mavasani Yeah sure

**Comment by pavanupb** [comment]
@mavasani I see AD0001 analyzer exception sometimes.

**Comment by mavasani** [comment]
> I see AD0001 analyzer exception sometimes.

I think if you rebuild, instead of build, you will see it everytime. You might be hitting https://github.com/microsoft/msbuild/issues/3046 when attempting to do repeated builds.

**Comment by pavanupb** [comment]
> > I see AD0001 analyzer exception sometimes.
> 
> I think if you rebuild, instead of build, you will see it everytime. You might be hitting [microsoft/msbuild#3046](https://github.com/microsoft/msbuild/issues/3046) when attempting to do repeated builds.

What would be the fix for the issue?

**Comment by mavasani** [comment]
> What would be the fix for the issue?

You mean the fix in your analyzer, correct? Can you figure out why your dependency injection package is not working in command line? Does it depend on some assembly which is only available when executed in VS IDE? One way to check would be to enable fusion logs and look at assembly bind failures through [fuslogvw.exe](https://docs.microsoft.com/en-us/dotnet/framework/tools/fuslogvw-exe-assembly-binding-log-viewer) and see the difference between execution in VS IDE and build.

**Comment by pavanupb** [comment]
> > What would be the fix for the issue?
> 
> You mean the fix in your analyzer, correct? Can you figure out why your dependency injection package is not working in build? Does it depend on some assembly which is only available when executed in VS IDE? One way to check would be to enable fusion logs and look at assembly bind failures through [fuslogvw.exe](https://docs.microsoft.com/en-us/dotnet/framework/tools/fuslogvw-exe-assembly-binding-log-viewer) and see the difference between execution in VS IDE and build.

Yes. I checked with the fusion logs. I see the AD0001 exception is not being thrown for all the applications. Even the fusion logs are not getting generated. Still, I see that not all warnings are being reported. Could it be because of the binding issue?

**Comment by sharwell** [comment]
@pavanupb The AD0001 message is printed with a stack trace and details regarding the exception that was thrown. Can you post the full error with the stack trace?

Due to an MSBuild bug, you might need to specify `/v:diag` or `/bl` for the command line build to show the full error.

**Comment by pavanupb** [comment]
@sharwell Below is the stack trace:

```
Analyzer 'CodeSharpenerCryptoAnalyzer.CodeSharpenerCryptoAnalyzerAnalyzer' threw an exception of type 'System.IO.FileLoadException' with message 'The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)'.
Exception occurred with following context:
Compilation: DotNetGoat
SyntaxTree: D:\Master_Thesis\WebGoat.NET-master\WebGoat\Content\PathManipulation.aspx.cs
SyntaxNode: string.Format(" bytes {0}-{1}/{2}" ... [InvocationExpressionSyntax]@[2771..2846) (73,58)-(73,133)

System.IO.FileLoadException: The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName)
   at CodeSharpenerCryptoAnalyzer.CodeSharpenerCryptoAnalyzerAnalyzer.AnalyzeMethodInvocationNode(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__58`1.<ExecuteSyntaxNodeAction>b__58_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
```

**Comment by sharwell** [comment]
I see you gave read access to @mavasani for the analyzer source code. Do you mind if we review it together?

**Comment by pavanupb** [comment]
> I see you gave read access to @mavasani for the analyzer source code. Do you mind if we review it together?

@sharwell I have added you as the collobrator.

**Comment by sharwell** [comment]
Yeah, this definitely looks like a case of dependencies not getting loaded. All dependencies not provided by the compiler (including `<PackageReference>`, `<ProjectReference>`, and `<Reference>` items) need to get included in the NuGet package under the package path **analyzers/dotnet/cs** (or **analyzers/dotnet/vb** for analyzing Visual Basic code). You can see an example of this here:

https://github.com/microsoft/vs-threading/blob/4c2ad53ba7ba16b0077d9b9f93d0bb5dff6f15fa/src/Microsoft.VisualStudio.Threading.Analyzers.CodeFixes/Microsoft.VisualStudio.Threading.Analyzers.CodeFixes.csproj#L19

https://github.com/microsoft/vs-threading/blob/4c2ad53ba7ba16b0077d9b9f93d0bb5dff6f15fa/src/Microsoft.VisualStudio.Threading.Analyzers.CodeFixes/Microsoft.VisualStudio.Threading.Analyzers.CodeFixes.csproj#L49-L63

**Comment by pavanupb** [comment]
@sharwell I am new to csproj configurations. So should I be including the two sections mentioned in my csproj file?

**Comment by pavanupb** [comment]
@mavasani I tried fixing the AD0001 exceptions in my analyzer. The issue still seems to persist while performing a whole solution analysis. I also checked fusion logs. There are no bindings errors reported for the analyzer.

**Comment by mavasani** [comment]
@pavanupb At this point, I feel the best way to root cause this for you to provide us a standalone repro that we can execute on our end to see the actual behavior and compare it with your expected behavior. Otherwise, it is hard to determine if the issue is with full solution analysis (and if so, what part of it), versus your analyzer, which seems to be a pretty non-trivial one.

**Comment by pavanupb** [comment]
@mavasani Sure. I will create a repo and share you with the example input of my analyzer.

**Comment by pavanupb** [comment]
@mavasani I created a separate repo of my analyzer and reduced the code keeping the logic that's causing an issue. My analyzer can be found in the repo : https://github.com/pavanupb/TaintAnalyzer. The example code on which I am running my analyzer can be found https://github.com/pavanupb/TaintAnalyzer/tree/master/Example-Code.

Let me know if you would require more information from my side.

**Comment by pavanupb** [comment]
> @mavasani I created a separate repo of my analyzer and reduced the code keeping the logic that's causing an issue. My analyzer can be found in the repo : https://github.com/pavanupb/TaintAnalyzer. The example code on which I am running my analyzer can be found https://github.com/pavanupb/TaintAnalyzer/tree/master/Example-Code. Now the analyzer does not have any NuGet references.
> 
> Let me know if you would require more information from my side.

**Comment by mavasani** [comment]
@pavanupb Taking a quick glance at your analyzer, I see following problems:

1. You need to remove any state (lists/dictionaries) that you store as fields on your analyzer. Both the following need to be removed: https://github.com/pavanupb/TaintAnalyzer/blob/8424ad8b8e1fff34f3a45d104c20272bebf6f683/SecureCodeAnalyzer/TaintFlowAnalyzer/TaintFlowAnalyzer.cs#L39-L41. I would recommend looking at https://github.com/dotnet/roslyn-sdk/blob/master/samples/CSharp/Analyzers/Analyzers.Implementation/StatefulAnalyzers/CompilationStartedAnalyzerWithCompilationWideAnalysis.cs to see how you should store mutable and immutable state in your analyzer for compilation wide analysis.
2. Your analysis should not depend on the order in which analyzer actions are invoked for specific nodes or symbols. For example, the code in https://github.com/pavanupb/TaintAnalyzer/blob/8424ad8b8e1fff34f3a45d104c20272bebf6f683/SecureCodeAnalyzer/TaintFlowAnalyzer/TaintFlowAnalyzer.cs#L67-L90. It seems to have different code paths based on whether or not containing symbol callback has executed, which is non-deterministic, given analyzers executes in parallel on symbols in compilation.

In short, you need to restructure your analysis so that CompilationStartAction creates required immutable state + fetches well known types, the intermediate actions registered on this start action update mutable state without relying or order in which analyzer callbacks are made and finally your CompilationEndAction processes all the mutable state to produce all diagnostics.

**Comment by mavasani** [comment]
I would also recommend you to take a glance at https://github.com/dotnet/roslyn/blob/master/docs/analyzers/Analyzer%20Actions%20Semantics.md

**Comment by pavanupb** [comment]
@mavasani Thank you so much for the review. As per the documentation https://github.com/dotnet/roslyn/blob/master/docs/analyzers/Analyzer%20Actions%20Semantics.md I restructured my analyzer. So first I am registering a CompilationStartAction. In CompilationStartAction I have registered a CodeBlockStartAction and a CompilationEndAction. I moved the code https://github.com/pavanupb/TaintAnalyzer/blob/14f00d980c23811751b8548faf8e6bbc485f1224/SecureCodeAnalyzer/TaintFlowAnalyzer/CompilationAnalyzer.cs#L53-L68 which depends on the order to CodeBlockStartAction as it should be invoked first before all the other syntax node actions. In the CodeBlockStartAction I am registering all the syntax node action https://github.com/pavanupb/TaintAnalyzer/blob/14f00d980c23811751b8548faf8e6bbc485f1224/SecureCodeAnalyzer/TaintFlowAnalyzer/CompilationAnalyzer.cs#L71-L75. Now I am adding all the diagnostics to a mutable list https://github.com/pavanupb/TaintAnalyzer/blob/14f00d980c23811751b8548faf8e6bbc485f1224/SecureCodeAnalyzer/TaintFlowAnalyzer/CompilationAnalyzer.cs#L22. At the CompilationEndAction I am reporting all the diagnostics https://github.com/pavanupb/TaintAnalyzer/blob/14f00d980c23811751b8548faf8e6bbc485f1224/SecureCodeAnalyzer/TaintFlowAnalyzer/CompilationAnalyzer.cs#L866. 

I have two mutable lists https://github.com/pavanupb/TaintAnalyzer/blob/14f00d980c23811751b8548faf8e6bbc485f1224/SecureCodeAnalyzer/TaintFlowAnalyzer/CompilationAnalyzer.cs#L21-L22. Since I need one list to be maintained for the entire session I am reinitializing it only if null(I am doing this since the CompilationStartAction would be invoked multiple times and would create a new instance of the list) https://github.com/pavanupb/TaintAnalyzer/blob/14f00d980c23811751b8548faf8e6bbc485f1224/SecureCodeAnalyzer/TaintFlowAnalyzer/CompilationAnalyzer.cs#L30. I debugged and checked to verify the order. The order was as follows
1. CompilationStartAction
2. CodeBlockStartAction
3. All the registered syntax node actions.
4. CodeBlockEndAction
5. CompilationEndAction

I see that the diagnostics are still not getting reported correctly with whole code analysis, but works perfectly with open documents. I read the document and sample programs. Am I still missing something?

**Comment by sharwell** [comment]
It looks like there are two lists that are declared `static`. These need to be changed to instance lists to ensure they are not reused from one compilation to the next:

https://github.com/pavanupb/TaintAnalyzer/blob/14f00d980c23811751b8548faf8e6bbc485f1224/SecureCodeAnalyzer/TaintFlowAnalyzer/CompilationAnalyzer.cs#L20-L21

> I see that the diagnostics are still not getting reported correctly with whole code analysis, but works perfectly with open documents. Am I still missing something?

There appeared to be some issues with the "Entire Solution" option for a bit. Can you also try right clicking in the solution and selecting **Analyze and Code Cleanup** &rarr; **Run Code Analysis on Solution** (you can do the same for just one project). This will run analyzers on one full compilation even if you don't have "Entire Solution" checked.

**Comment by pavanupb** [comment]
@sharwell I Changed from static to instance lists. Tried with **Analyze and Code Cleanup → Run Code Analysis on Solution** option, but I still see the same behavior.

**Comment by sharwell** [comment]
It looks like the analyzer dependencies were not included as analyzer assets:
https://github.com/pavanupb/TaintAnalyzer/blob/c7200b71ca2a54ccd05e0a62062e20faff9401ae/SecureCodeAnalyzer/CodeAnalyzerInstaller/source.extension.vsixmanifest#L20

**Comment by pavanupb** [comment]
> ~It looks like the analyzer dependencies were not included as analyzer assets: https://github.com/pavanupb/TaintAnalyzer/blob/c7200b71ca2a54ccd05e0a62062e20faff9401ae/SecureCodeAnalyzer/CodeAnalyzerInstaller/source.extension.vsixmanifest#L20~
> 
> Actually it looks like the dependency inject dependency is still declared, but isn't used.

Yeah, I need to remove it. Now in this sample analyzer, I am not using any Nuget packages

**Comment by sharwell** [comment]
The next step for me would be creating a test project, and writing a simple test using [Microsoft.CodeAnalysis.Testing](https://github.com/dotnet/roslyn-sdk/tree/master/src/Microsoft.CodeAnalysis.Testing) showing some diagnostics I expect to appear. If the diagnostics appear in the test but do not appear in the IDE, it should be easy to narrow down the cause. Likewise, if the diagnostics are missing during test execution then you can easily debug the analyzer from Test Explorer.

**Comment by pavanupb** [comment]
@sharwell Is it the same test project that comes shipped with the Analyzer+Codefix template in VS 2019?

**Comment by sharwell** [comment]
Yes, but the template I'm referring to first shipped in 16.7 Preview 4 (which is the latest preview). There is a bug in the project creation dialog, so to use it you'll need to first create an empty solution, and then add a new project to it from the template.

**Comment by pavanupb** [comment]
I installed the latest preview of Visual Studio. I do not see a testing template Microsoft.CodeAnalysis.Testing. Should I need to install any additional features for it?

**Comment by pavanupb** [comment]
@sharwell How can I send multiple documents with the new testing framework?. The previous VerifyDiagnsotics had an overloaded method that would take an array of string. The new one seems to have one overload which takes in a single string argument. It would be best to test with multiple documents to reproduce the issue.

**Comment by sharwell** [comment]
```
await new VerifyCS.Test {
  TestState = {
    Sources = { source1, source2, source3 }
  }
}.RunAsync();

**Comment by pavanupb** [comment]
@sharwell After running the test cases I was able to crackdown the issue. What I am doing is relying on code bock end actions. I was initializing some variables at code block start action then doing analysis on various registered syntax node actions and finally storing all the analysis results of the particular code block into a dictionary in the code block end action. When I debugged the code with the test case I found that the code block start action for the second method is called even before calling the code block end action of the first method. When the code block end actions are called in the right order the diagnostics get reported correctly.

**Comment by mavasani** [comment]
> When I debugged the code with the test case I found that the code block start action for the second method is called even before calling the code block end action of the first method. When the code block end actions are called in the right order the diagnostics get reported correctly.

Ah, so you are relying on unspecified ordering of actions. There is no ordering guarantee between two different code block start action callbacks - only guarantee is that code block end actions for a specific code block is called after code block start actions and intermediate syntax/operation actions for _the same code block_.

>  But how is it invoked in the right order when I do single document analysis?.

That seems to be due to the case that we currently execute open file analysis in a non-concurrent fashion because it runs within devenv.exe process, as oppose to project analysis, which runs concurrently on the whole project in ServiceHub.RoslynCodeAnalysisService process. This will soon change with https://github.com/dotnet/roslyn/pull/45607, at which point you will see your analyzer failing consistently for both open file and full project analysis :-).

You need to adjust your analyzer so that you do not rely on any ordering between action callbacks for separate code blocks.

**Comment by pavanupb** [comment]
Okay, :-) Seems to change a lot of logic in my analyzer. What would be the best way to maintain a list for an entire compilation?. Meaning I would be requiring the analysis results of the previous document to analyze the current document.

**Comment by mavasani** [comment]
> For instance, I am doing validation on the order of innovation of methods in the cryptographic library and reporting a diagnostic if not invoked in the secure order. This would not become possible with the code block end action not being invoked in the right order correct?

I think you are getting confused between ordering of actions for a single code block and across multiple code blocks. Let us consider

```csharp
class C
{
  void M1()
  {
    SomeMethod();
  }

}

**Comment by mavasani** [comment]
> I am doing validation on the order of innovation of methods in the cryptographic library and reporting a diagnostic if not invoked in the secure order

You can register an OperationBlockStartAction, and then for each operation block in `context.OperationBlocks`, use an OperationVisitor/OperationWalker to walk operations in the order in source. Another approach would be to potentially create a [ControlFlowGraph](http://sourceroslyn.io/#Microsoft.CodeAnalysis/Operations/ControlFlowGraph.cs,16) and then walk the basic blocks containing lowered operations. It purely depends on the kind of control flow/data flow analysis you are performing.

**Comment by pavanupb** [comment]
> > For instance, I am doing validation on the order of innovation of methods in the cryptographic library and reporting a diagnostic if not invoked in the secure order. This would not become possible with the code block end action not being invoked in the right order correct?
> 
> I think you are getting confused between ordering of actions for a single code block and across multiple code blocks. Let us consider
> 
> ```cs
> class C
> {
>   void M1()
>   {
>     SomeMethod1();
>   }
> 
>   void M2()
>   {
>     SomeMethod2();
>   }
> }
> ```
> 
> It is guaranteed that code block end for `M1` will be invoked after code block start for `M1` and also after actions for invocation `SomeMethod1()`. Similarly, code block end for `M2` will be invoked after code block start for `M2` and also after actions for invocation `SomeMethod2()`. But there is no guarantee of ordering between a pair of actions such that one of them belongs to `M1` and another to `M2`.

Okay. But there is no guarantee that start block action gets M1 first and then M2 right?

**Comment by pavanupb** [comment]
I have two methods M1 and M2 as shown below:
class A
{
      void main()
     {
        int a = 10;
        int b = 20;
        result = foo(a, b);
     }
}
class B
{
     foo(int p, int q)
     {
         //do something
     }
}

So I would like to analyze my code in an interprocedural manner. After the first two statements of the main function are analyzed, I would like to analyze the statements of foo() in class B. I was relying on thinking the start block action gets analyzed first with the statements of main() and then statement of foo(). But this would not work, right?

**Comment by mavasani** [comment]
> So I would like to analyze my code in an interprocedural manner. After the first two statements of the main function are analyzed, I would like to analyze the statements of foo() in class B. I was relying on thinking the start block action gets analyzed first with the statements of main() and then statement of foo(). But this would not work, right?

Yep, you should not rely on order of calls for interprocedural analysis.

**Comment by pavanupb** [comment]
@mavasani Thank you so much for clearing the Roslyn concepts. I would like to explore the pointer analysis available in Roslyn. I could not find a document that explains the points-to analysis and copy analysis results. Is there any document available other than https://github.com/dotnet/roslyn-analyzers/blob/master/docs/Writing%20dataflow%20analysis%20based%20analyzers.md which explains more about the points-to analysis and alias analysis.

**Comment by mavasani** [comment]
@pavanupb You can refer to https://github.com/dotnet/roslyn-analyzers/blob/master/docs/Writing%20dataflow%20analysis%20based%20analyzers.md. We also ship a NuGet package https://www.nuget.org/packages/Microsoft.CodeAnalysis.AnalyzerUtilities that exposes public APIs for PointsTo analysis and other well-known analyses. In fact, the package also contains an implementation of Tainted dataflow analysis for security rules, but the API is internal, not public: https://github.com/dotnet/roslyn-analyzers/blob/master/src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/TaintedDataAnalysis.cs#L25. Also tagging @dotpaul who owns TaintedDataAnalysis.

**Comment by pavanupb** [comment]
@mavasani Is there any technical paper on pointer analysis implementation in Roslyn. I am interested to know the internals of pointer analysis like whether a call strings or functional approach is used to perform an interprocedural analysis and how a call graph is built.

**Comment by pavanupb** [comment]
Why is the points-to analysis not containing the points-to set of any variables of a callee procedure?.  In the example code, the line https://github.com/pavanupb/SecureCodeAnalyzer/blob/5547ca268e8c4569226362ab2183481d7ad0ac76/Example-Code-2/AesEncOnly/Program.cs#L24 contains a call to a procedure. I do not see any points-to set for the variables of the called procedure. Am I missing any configuration in my analyzer while performing points-to analysis?. 
I am able to see the same behavior with the alias analysis. I am performing an alias analysis at line https://github.com/pavanupb/SecureCodeAnalyzer/blob/c6e56bd38327f35e39d622256450159e8673c049/SecureCodeAnalyzer/TaintFlowAnalyzer/CompilationAnalyzer.cs#L107.

**Comment by mavasani** [comment]
> Is there any technical paper on pointer analysis implementation in Roslyn. 

No, the algorithm is not based on specific paper.
 
> Why is the points-to analysis not containing the points-to set of any variables of a callee procedure

We perform a performance optimization at callsites and return sites to trim the points to sets to only the set of abstract locations that are accessible from the subsequent method being called/returned to.

**Comment by pavanupb** [comment]
Without the points-to set, alias info of a callee and without an interprocedural CFG, it would be difficult for a taint analysis to decide whether the receiver variable at a call site (For instance: the receiver variable at https://github.com/pavanupb/SecureCodeAnalyzer/blob/5547ca268e8c4569226362ab2183481d7ad0ac76/Example-Code-2/AesEncOnly/Program.cs#L24) is tainted or not.

**Comment by mavasani** [comment]
> Without the points-to set, alias info of a callee and without an interprocedural CFG

NOTE: We do not completely remove the points to set at callsites or return sites - we only remove the ones which are never accessible from the called/returned to method. For your example, the invocation `encryptDecrypt.EncryptStringToBytes_Aes` should have the the points to value of `encryptDecrypt` in the `this` instance of the called method, and if any of the fields/properties of `encryptDecrypt` where assigned in the caller, then points to values of those fields/properties (with the  `this` instance as its instance location) should be present in the set. A lack of points-to-value indicates they were not assigned in the callee, hence has unknown value.

**Comment by pavanupb** [comment]
Okay. The lack of points-to set not available for variables at line https://github.com/pavanupb/SecureCodeAnalyzer/blob/5547ca268e8c4569226362ab2183481d7ad0ac76/Example-Code-2/AesEncOnly/AesEncryption.cs#L22 and at line https://github.com/pavanupb/SecureCodeAnalyzer/blob/5547ca268e8c4569226362ab2183481d7ad0ac76/Example-Code-2/AesEncOnly/AesEncryption.cs#L12 in the callee is due to they are not being used in the caller method. Is that correct?

**Comment by mavasani** [comment]
Yes, that is correct. If you pass that variable as an argument, or even pass some other variable such that the other variable is directly or indirectly reachable through the passed variable, the points to set should contain the value for that variable.

**Comment by pavanupb** [comment]
Created a simple example for a demonstration. The variables returned from the callee is used in the caller at line https://github.com/pavanupb/SecureCodeAnalyzer/blob/0fe7ae7440cc69d6a1294c787bd6aff021f11da3/Example-Code-3/AliasAnalysisTest/Program.cs#L13. The points-to analysis returns only for AliasAnalysisTest and for the parameter args at line https://github.com/pavanupb/SecureCodeAnalyzer/blob/0fe7ae7440cc69d6a1294c787bd6aff021f11da3/Example-Code-3/AliasAnalysisTest/Program.cs#L7. 
Also performed a copy analysis. The alias analysis contains the parameter args at line https://github.com/pavanupb/SecureCodeAnalyzer/blob/0fe7ae7440cc69d6a1294c787bd6aff021f11da3/Example-Code-3/AliasAnalysisTest/Program.cs#L7 with a kind "KnowReferenceCopy". Even though the parameter args is not being used why is it present as a "KnownReferenceCopy"

**Comment by mavasani** [comment]
You will need to be more clear on what you are expecting in the points to set. Strings are tracked as value copies, so will not be part of points-to-set. Where is `GetValues` defined? If it is outside the current project/assembly boundary, then no interprocedural analysis is performed as analyzers can only look at sources inside the current compilation.

**Comment by pavanupb** [comment]
> You will need to be more clear on what you are expecting in the points to set. Strings are tracked as value copies, so will not be part of points-to-set. Where is `GetValues` defined? If it is outside the current project/assembly boundary, then no interprocedural analysis is performed as analyzers can only look at sources inside the current compilation.

The `GetValues` is defined within the same project.

**Comment by mavasani** [comment]
> The GetValues is defined within the same project.

Would you be able to create a small unit test to demonstrate the issue? For example, see some tests at https://github.com/dotnet/roslyn-analyzers/blob/master/src/Utilities.UnitTests/FlowAnalysis/Analysis/PropertySetAnalysis/PropertySetAnalysisTests.cs. If you can create a unit test with your expected points-to-set for your example, and file an issue on roslyn-analyzers repo, it will be much more actionable and easier to investigate.

**Comment by pavanupb** [comment]
> > The GetValues is defined within the same project.
> 
> Would you be able to create a small unit test to demonstrate the issue? For example, see some tests at https://github.com/dotnet/roslyn-analyzers/blob/master/src/Utilities.UnitTests/FlowAnalysis/Analysis/PropertySetAnalysis/PropertySetAnalysisTests.cs. If you can create a unit test with your expected points-to-set for your example, and file an issue on roslyn-analyzers repo, it will be much more actionable and easier to investigate.

Sure will do create a unit test with my expected points-to set.

**Comment by pavanupb** [comment]
Does Roslyn perform a points-to analysis for a method present in a different assembly? For instance at line:https://github.com/pavanupb/SecureCodeAnalyzer/blob/5547ca268e8c4569226362ab2183481d7ad0ac76/Example-Code-2/AesEncOnly/AesEncryption.cs#L27

**Comment by mavasani** [comment]
No, there is no interprocedural analysis outside the current source assembly.

**Comment by pavanupb** [comment]
Is the interprocedural analysis conducted something similar to a call strings approach(value-based approach) where each callee is analyzed as a separate context limiting this context length to 3?

**Comment by mavasani** [comment]
> where each callee is analyzed as a separate context

Each callee is analyzed with context from the call site. There is a default length of method call that gets analyzed for performance reasons, but this is configurable both by the end users (see [here](https://github.com/dotnet/roslyn-analyzers/blob/master/docs/Analyzer%20Configuration.md#maximum-method-call-chain-length-to-analyze-for-interprocedural-dataflow-analysis) and from API users (see [here](https://github.com/dotnet/roslyn-analyzers/blob/30c2edf4d3bac102574f29a8b4ba04a2e3e21f1c/src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.cs#L33) and [here](https://github.com/dotnet/roslyn-analyzers/blob/30c2edf4d3bac102574f29a8b4ba04a2e3e21f1c/src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/InterproceduralAnalysisConfiguration.cs#L40-L61)).

**Comment by pavanupb** [comment]
Okay. Does the points-to analysis results dictionary mean that a particular allocation site is represented as key and the variables that points-to the allocation site are represented as values?

**Comment by mavasani** [comment]
Key: https://github.com/dotnet/roslyn-analyzers/blob/master/src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/AnalysisEntity.cs#L15-L33

Value: https://github.com/dotnet/roslyn-analyzers/blob/master/src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAbstractValue.cs#L11-L15

**Comment by pavanupb** [comment]
Does the copy-analysis tell which are the variables that alias with each other? Does copy-analysis as well works only with object properties.?. For instance I have a couple of statements 
```
byte[] secret = { 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16 };

            DemoClass demoClass = new DemoClass();
            demoClass.ByteValue = secret;  
```

The Copy-analysis is returning only `demoClass.ByteValue` as "knowReferenceCopy". I was expecting both `demoClass.ByteValue` and secret to be of type "KnownReferenceCopy"

**Comment by mavasani** [comment]
NOTE: Copy analysis is still in experimental phase, hence disabled by default for all analyses/analyzers. I wouldn't be surprised if it was not as precise as your expectations.

**Comment by pavanupb** [comment]
Ah okay. Thanks

**Comment by pavanupb** [comment]
@mavasani Is Roslyn using an interprocedural-CFG while performing a points-to analysis?.
