### ISSUE TITLE
Wrong IDE0130 message "Namespace 'Foo' does not match folder structure, expected 'Foo'"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#55014]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Wrong-IDE0130-message-Namespace-Foo-d/1479964)._

---
[regression] [worked-in:16.11?]
I have a .NET 5.0 project which has app which has default namespace 'Microsoft.BigSolutionGenerator'. Each source file shows 

```
IDE0130: "Namespace "Microsoft.BigSolutionGenerator" does not match folder structure, expected "Microsoft.BigSolutionGenerator."
```

... although it already has namespace Microsoft.BigSolutionGenerator. Lightbulb offers to replace namespace with `Microsoft.BigSolutionGenerator.Microsoft.BigSolutionGenerator`

! [image.png] (https://aka.ms/dc/image?name=B2b8b22d62a694eb6acf89007e304b951637624074571776408_20210720-125057-image.png&tid=2b8b22d62a694eb6acf89007e304b951637624074571776408)

---
#### Feedback Bot on 7/20/2021, 11:41 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 7/21/2021, 10:09 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by Youssef1313** [comment]
Related to the second note in https://github.com/dotnet/roslyn/issues/54757.

**Comment by tuananh-le** [comment]
We face the same issue in our .NET 5 project as well using the mcr.microsoft.com/dotnet/sdk:5.0 base image to build in docker.

**Comment by Youssef1313** [comment]
@ryzngard Was this already fixed?

**Comment by tuananh-le** [comment]
@Youssef1313 : we just had to use the older image 5.0.303 for now.

**Comment by andrewflierman** [comment]
I can confirm that image 5.0.303 works

**Comment by gabrielmaldi** [comment]
This also affects `dotnet format`:
```
warning IDE0130: Namespace "Some.Name.Space" does not match folder structure, expected "Some.Name.Space." [/path/to/repo/Some.Name.Space/Some.Name.Space.csproj]
```
```
Unhandled exception: System.NotSupportedException: Changing document properties is not supported
   at Microsoft.CodeAnalysis.Workspace.CheckAllowedProjectChanges(ProjectChanges projectChanges)
   at Microsoft.CodeAnalysis.Workspace.CheckAllowedSolutionChanges(SolutionChanges solutionChanges)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution, IProgressTracker progressTracker)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.TryApplyChanges(Solution newSolution, IProgressTracker progressTracker)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.TryApplyChanges(Solution newSolution)
   at Microsoft.CodeAnalysis.Tools.CodeFormatter.FormatWorkspaceAsync(FormatOptions formatOptions, ILogger logger, CancellationToken cancellationToken, String binaryLogPath) in /_/src/CodeFormatter.cs:line 99
   at Microsoft.CodeAnalysis.Tools.Program.Run(String workspace, Boolean noRestore, Boolean folder, Boolean fixWhitespace, String fixStyle, String fixAnalyzers, String[] diagnostics, String verbosity, Boolean check, String[] include, String[] exclude, String report, Boolean includeGenerated, String binarylog, IConsole console) in /_/src/Program.cs:line 185
   at System.CommandLine.Invocation.CommandHandler.GetExitCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass27_0.<<UseVersionOption>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by ryzngard** [comment]
These are fixed by: 

#55559 (fixes the codefix incorrectly handling documents at root) 
#55424 (fixes the diagnostic being reported incorrectly)

**Comment by CasperTDK** [comment]
That is great, but I see no new docker image with the fix? I have had to hardcore the version to `5.0.300-buster-slim` instead of `5.0-buster-slim`

**Comment by andrewflierman** [comment]
Yup, I tried also with `mcr.microsoft.com/dotnet/sdk:5.0` but failed

**Comment by edwiles** [comment]
Has this made it through to a .NET SDK version as yet? It doesn't seem to be fixed in 5.0.401. I see it's in Roslyn 17.0 P4 but not sure how this maps to .NET SDK version. Thanks

**Comment by the-real-joakim-lindberg** [comment]
I still have the issue in 5.0.402, so it is not fixed.
@edwiles I did a global suppression just for the root namespace, which solved it for the time being.
```csharp
[assembly: SuppressMessage("Style", "IDE0130:Namespace does not match folder structure", Justification = "It cannot handle items in root namespace", Scope = "namespace", Target = "~N:MyCompany.MyApp")]```

**Comment by tomas-cs** [comment]
This issue is still present in SDK 5.0.405, how come this bug is closed?

**Comment by ryzngard** [comment]
@tomas-cs  can you provide an example solution where you're seeing this? I was unable to reproduce this issue using 
[this solution](https://github.com/dotnet/roslyn/files/8051335/namespacetest.zip)

**Comment by tomas-cs** [comment]
Strangely enough, it doesn't appear in my solution either. But it was there at the moment I wrote previous comment.. Not sure what happened, looks good now. I'll post again when the issue reappears. Thank you for looking into it 👍

**Comment by SvendK** [comment]
I'm also having this issue. It somehow wants a dot at the end (OP issue title missed that).

Visual Studio 2019 v.16.11.7 with two projects in a solution:
1) WPF Application for .NET Core
2) Class library for .NET Standard or .NET Core
Each in their own simple namespace, both are having this issue. 

Not sure what kind of info I can give you?

![image](https://user-images.githubusercontent.com/3720082/158242669-bbb234be-edc7-41a0-aac1-8e163d63a312.png)

![image](https://user-images.githubusercontent.com/3720082/158242146-c531ab1e-cc60-4e00-bd82-4afbc4abc368.png)

![image](https://user-images.githubusercontent.com/3720082/158242161-1e378122-2c20-40d4-bf69-a8216fec7b5c.png)

**Comment by ryzngard** [comment]
@SvendK this should be fixed in later versions of VS. Unfortunately it means we're not backporting this fix.

For the editorconfig related issue, are you see that `dotnet_style_namespace_match_folder = false` doesn't work? or is something else happening?

**Comment by SvendK** [comment]
Sorry for the late reply.

Thanks for acknowleding the bug. I'll live with it until my workplace upgrade to VS2022 :-)

About the suppresion: Revisiting the project where I had the problem, the suppresion now works. Maybe I had to restart VS2019 before it worked? Nothing was happening after changing the suppresion via the lightbulb menus, the namespace was still underlines with the "suggestion" marking. But now there is now marking, so I'm happy :-)

I'll check the next time I'm doing a new project, whether it's a restart that's necessary after the lightbulb suppresion change.

**Comment by rik-smeets** [comment]
I'm also having this issue with a .NET 6 project. In Visual Studio the code fix works fine, but when triggered from [dotnet format](https://github.com/dotnet/format) I do get the aforementioned exception. Example solution can be found [here](https://github.com/rik-smeets/DotNetFormatTest).

Exception that occurs when running `dotnet format` on the solution:
```
Unhandled exception: System.NotSupportedException: Changing document properties is not supported
   at Microsoft.CodeAnalysis.Workspace.CheckAllowedProjectChanges(ProjectChanges projectChanges)
   at Microsoft.CodeAnalysis.Workspace.CheckAllowedSolutionChanges(SolutionChanges solutionChanges)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution, IProgressTracker progressTracker)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.TryApplyChanges(Solution newSolution, IProgressTracker progressTracker)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.TryApplyChanges(Solution newSolution)
   at Microsoft.CodeAnalysis.Tools.CodeFormatter.FormatWorkspaceAsync(FormatOptions formatOptions, ILogger logger, CancellationToken cancellationToken, String binaryLogPath)
   at Microsoft.CodeAnalysis.Tools.FormatCommandCommon.FormatAsync(FormatOptions formatOptions, ILogger`1 logger, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Tools.Commands.RootFormatCommand.FormatCommandDefaultHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass27_0.<<UseVersionOption>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
```
