### ISSUE TITLE
Getting CS8168 and CS8350 in .NET 7 RC1 for code that compiled on .NET 7 preview 7 and .NET 6

### ISSUE THREAD

**Issue by nicro950** [dotnet/roslyn#64421]
**Version Used**: 

7.0.100-rc.1.22431.12

**Steps to Reproduce**:

1. Trying to compile the following code
```csharp
public ref struct TestingStruct { }

public static void Caller()
{
    var str = new TestingStruct();
    var num = 1;
    Func(ref str, ref num);
}

public static void Func(ref TestingStruct param1, ref int param2) { }
```

[SharpLab](https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4AEBMBGAsAKAIPWwDYACdAFnIGEIAbBgUwCcAKASgIG8DyB5AG4RW5AM4AXMQF5yMZgHdyAFWZTYAcwDK0gK4BjSVwDc/QSLEw9YcnOxn8gygFZ2rZgDMJ0uOQ/e1mCcjgC+RPgkFNSu7l6q6pJauqyGkuQADqIQYNh+AeSw6VmsOZjc+HyE+OHV6ADM/vFSqUYJGjA6+ka8BKFAA===)

Result in the following errors: 

    error CS8168: Cannot return local 'num' by reference because it is not a ref local
    error CS8350: This combination of arguments to 'Func(ref TestingStruct, ref int)' is disallowed because it may expose variables referenced by parameter 'param2' outside of their declaration scope

**Expected Behavior**:

That the code builds like it do in .NET 6 and .NET 7 preview 7

**Actual Behavior**:

Results in CS8168 and CS8350

**Comment by Youssef1313** [comment]
Looks similar to https://github.com/dotnet/roslyn/issues/64000

**Comment by Sergio0694** [comment]
This is fixed in the latest version of Roslyn (following the return-only work spec'd in https://github.com/dotnet/csharplang/pull/6450). Both those two `ref` parameters have RSTE to return-only, and `param2` can't possibly escape through `param1` because of that, so the code is valid. You can try for yourself referencing the compiler version `4.4.0-3.22479.16` or greater, and the code will build as expected 🙂

**Comment by nicro950** [comment]
I testet the 4.4.0-3.22479.16 and it worked without problems then :) It also looks like all the newer 4.4.x compilers worked fine, but when i tried the 4.5.x compilers then the problem reappeared. Maybe it is not yet fixed for that branch of compilers? Also adding scoped to the second parameter (param2) looked like it fixed the problem: [Sharplab](https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4AEBMBGAsAKAIPWwDYACdAFnIGEIAbBgUwCcAKASgIG8DyB5AG4RW5AM4AXMQF5yMZgHdyAFWZTYAcwDK0gK4BjSVwDc/QSLEw9YcnOxn8gygFZ2rZgDMJ0uOQ/e1mCcjgC+RPgkFNSu7l6q6pJauqyGkuQADqIQYNh+4gYA9hnMCP7xsOlZrDmY3Ph8hPjhTegAzOXeUqlGCRowOvpGvAShQA==)

**Comment by jaredpar** [comment]
Thanks for taking the time to report. This is a duplicate of #64365

>  It also looks like all the newer 4.4.x compilers worked fine, but when i tried the 4.5.x compilers then the problem reappeared.

This is likely just code flow having not caught up yet. It can take a bit of time for the change to migrate between the branches. It will be there in the next week if it's not already there.
