### ISSUE TITLE
IDE0055 for comment on new line not indented to comments at end of previous line?

### ISSUE THREAD

**Issue by jez9999** [dotnet/roslyn#65247]
I'm getting an IDE0055 for any comment on a new line not indented to the level of a comment at the end of a previous line.  Example:

![image](https://user-images.githubusercontent.com/793830/200173912-dd974daf-ec46-4a0c-8f2b-1ad645a32c62.png)

I simply don't think this should be enforced as a formatting rule.  Is there any .editorconfig configuration I can add to stop this requirement?  I can't see anything on the MS website.  If not, could one be introduced to turn the requirement off?

**Comment by sharwell** [comment]
💡 Adding a blank line before the TODO comment should fix this.

We already fixed the case where the comment is immediately followed by a line of code (#29482), but in this case it's followed by a blank line.

**Comment by jez9999** [comment]
Yeah but I don't want to follow it by a blank line.

**Comment by sharwell** [comment]
@jez9999 I am not able to reproduce this currently. I'm not sure when the behavior changed.

**Comment by jez9999** [comment]
> @jez9999 I am not able to reproduce this currently. I'm not sure when the behavior changed.

What version of Visual Studio are you using?  I just upgraded to 17.9.6 and still get this behaviour.

**Comment by sharwell** [comment]
I'm using Version 17.11.0 Preview 1.0 [34803.261.main].

Are you by any chance using hard tabs?

**Comment by jez9999** [comment]
Yes.

**Comment by sharwell** [comment]
Thanks! I'm going to mark this as a duplicate of a newer but more specific issue report.

**Comment by sharwell** [comment]
Duplicate of #72966

**Comment by JDoucette** [comment]
I am writing here since the ticket I opened:
https://developercommunity.visualstudio.com/t/Incorrect-auto-align-comment-only-line-t/10537710
was de-duped against this one.  I voted that was incorrect, but I see the response to that shows as private.  I wonder if you folks can read it or not.
