### ISSUE TITLE
Use argument types to guide Signature Help

### ISSUE THREAD

**Issue by dpoeschl** [dotnet/roslyn#6713]
If there are two overloads:

```
void M(int x, string y, string z)
void M(string x, int y, int z)
```

with an in-process call site like

```
M("", 5, 
```

then Signature Help should prefer showing the `M(string, int, int)` overload (or filter out all non-matching overloads?)

This could include preferring overloads with more parameters over overloads with the exact number of parameters. The compiler doesn't inherently support partial-argument-based overload resolution in this way, but we could take each overload and produce a call site with the set of known types so far, filling in the remaining arguments with the exact types in those positions for that overload. The overloads that come back as the targets of these binding checks could then be preferred.

**Comment by dpoeschl** [comment]
We should get (closer to) consensus on the exact design of this enhancement before picking an implementation.

**Comment by DustinCampbell** [comment]
We just received a request for this on Visual Studio Feedback, so giving this a +1.

**Comment by Pilchie** [comment]
Added to #7056 so we don't forget.  Agree that we should do this when we can

**Comment by dpoeschl** [comment]
Also reported at https://developercommunity.visualstudio.com/content/problem/102063/intellisense-provides-wrong-enum-for-messageboxsho.html (https://devdiv.visualstudio.com/DevDiv/NET%20Developer%20Experience%20IDE/_workitems?_a=edit&id=485841&triage=true)

**Comment by dpoeschl** [comment]
Another request: https://developercommunity.visualstudio.com/content/problem/247213/intellisense-still-not-working-properly-with-overl.html?childToView=250508#comment-250508

**Comment by sharwell** [comment]
@jcouv Was this issue fixed by your recent work in the area?

**Comment by jcouv** [comment]
Yes, this should have been fixed by https://github.com/dotnet/roslyn/pull/25835 (in 16.0 milestone).
It may be good to add tests for the various scenarios that were requested (see links above) to validate and close. Or we can close this and re-open after we get some firsthand experience with a dev16 preview (to see how the experience feels).

The basic design is that the ChangeSignature provider selects the symbol returned by the compiler's `GetSymbolInfo`. Such selections are then incorporated to the current state (previous selection, explicit user selection) with a new precedence logic: `last explicit choice (from up/down arrows input) -> provider choice -> last implicit choice? -> first/default`
More details in that PR.

**Comment by floele** [comment]
Hi @jcouv, I'm looking forward to the fix for this problem 👍 
I tried the current preview of 2019 and didn't notice any improvement yet, is this shipping with a later release?

**Comment by jcouv** [comment]
@floele You're right, this is still not working. I'll investigate further.

![image](https://user-images.githubusercontent.com/12466233/49969275-07fc4180-fedd-11e8-866b-8cc5d175b1c5.png)

**Comment by TanvirArjel** [comment]
Today I have spent two hours by investigating to find out why my library method overloads not picking the correct overload in IntelliSense. Finally, I have come here and understood that's not my library design fault. It's a compiler bug!!

**Comment by ElectricThanhTung** [comment]
I have same issue. I hope it will be fixed. It has been 8 years sence this issue has raised.
