### ISSUE TITLE
Reconsider license for Microsoft.CommonLanguageServerProtocol.Framework and related projects

### ISSUE THREAD

**Issue by bjorkstromm** [dotnet/roslyn#68463]
With the [announcement of the new C# extension](https://github.com/dotnet/vscode-csharp/issues/5708) I'd suggest revisiting the license for [Microsoft.CommonLanguageServerProtocol.Framework](https://github.com/dotnet/roslyn/blob/826e1770eedb6d8d44a054c9e3ea6569e7ec5970/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/License.txt). I'd also suggest revisiting dependencies having similar licenses, such as [Microsoft.VisualStudio.LanguageServer.Protocol](https://www.nuget.org/packages/Microsoft.VisualStudio.LanguageServer.Protocol/17.2.8/License).

The `MICROSOFT VISUAL STUDIO ADD-ONs and EXTENSIONS` license is problematic because it states that the software can be used solely within Visual Studio products. This leaves other editors such as VIM, emacs, VSCodium, etc. out in the cold, because these editors can't use the new improved language server.

**Comment by dibarbet** [comment]
There's a separate conversation about this going on.  Nothing to share right now, but will update this issue when I do have something.

**Comment by bjorkstromm** [comment]
> @dibarbet ? I believe we discussed this before. There's no real need for this reference, except to make it easy to generate some serialization types. We can either see about getting that package to be licensed in a compatible fashion, or we can move off of it and just write json directly. Want to drive this in next LSP meeting?

Please not that it's not only `Microsoft.VisualStudio.LanguageServer.Protocol` that has this problematic license. [CLaSP](https://github.com/dotnet/roslyn/tree/826e1770eedb6d8d44a054c9e3ea6569e7ec5970/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework) also uses similar license. That's probably easier to change, since it lives in this repository.

**Comment by omajid** [comment]
We discovered in https://github.com/dotnet/source-build/issues/3530 that this issue is a blocker for the distro maintainers looking to use the .NET VMR.

As far as we can tell, roslyn needs Microsoft.CommonLanguageServerProtocol.Framework as part of its overall build - we can't just exclude/delete it as a local workaround. And since this package (along with rosyln) is a part of the .NET VMR, the proprietary license here becomes a part of the VMR. This proprietary license is unacceptable to various source-build partners.

**Comment by omajid** [comment]
Can we mark this as resolved by https://github.com/dotnet/roslyn/pull/68942 ?

**Comment by bjorkstromm** [comment]
> @bjorkstromm I believe we already resolved the issue which is under control of this repository, so I'm marking this one as fixed by #68942.

No. There is still a dependency on [Microsoft.VisualStudio.LanguageServer.Protocol](https://www.nuget.org/packages/Microsoft.VisualStudio.LanguageServer.Protocol) in the LSP host itself:

https://github.com/dotnet/roslyn/blob/a518ae1c330c028cafb408d3ed5d55b3de4a59e2/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Microsoft.CodeAnalysis.LanguageServer.csproj#L61

And in one of the dependent projects:

https://github.com/dotnet/roslyn/blob/a518ae1c330c028cafb408d3ed5d55b3de4a59e2/src/Features/LanguageServer/Protocol/Microsoft.CodeAnalysis.LanguageServer.Protocol.csproj#L22-L24

IANAL, but as long as there's a dependency on those packages, the LSP host itself is also licensed under the same license.

**Comment by CyrusNajmabadi** [comment]
We're working on uncoupling that as we speak :)

**Comment by bjorkstromm** [comment]
> We're working on uncoupling that as we speak :)

Nice! Thank you @CyrusNajmabadi!! 🎉

**Comment by KennethHoff** [comment]
> We're working on uncoupling that as we speak :)

Did this ever happen by the way? I see there is an issue that was created that still isn't closed

**Comment by 333fred** [comment]
Yes, that was done in https://github.com/dotnet/roslyn/pull/68990. I closed the linked issue.
