### ISSUE TITLE
Primary constructor variable null in debugger

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn#70730]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Primary-constructor-variable-null-in-deb/10497771)._

---
When debugging in 17.8 preview 4, primary constructor paramters are always "null" in the debugger.

![image.png](https://aka.ms/dc/image?name=B24e2760fb0944058992839c5c68c0500638336455369582276_20231023-101213-image.png&tid=24e2760fb0944058992839c5c68c0500638336455369582276)

---
#### Feedback Bot on 10/23/2023, 01:14 AM: 

(private comment, text removed)
#### Feedback Bot on 10/25/2023, 09:36 AM: 

(private comment, text removed)
#### Isadora Rodopoulos [MSFT] on 10/25/2023, 05:03 PM: 

(private comment, text removed)
#### Feedback Bot on 11/8/2023, 08:40 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by AlekseyTs** [comment]
I think #70587 addresses this issue.

**Comment by paulnsk** [comment]
I am using 17.8.0 production version and just encountered this same issue.

![image](https://github.com/dotnet/roslyn/assets/39160578/f117282e-66c7-43a9-9ee1-148bc45c12cc)

I think this should be reopened

**Comment by CyrusNajmabadi** [comment]
@paulnsk you're not testing the release with the fix in it.

**Comment by paulnsk** [comment]
@CyrusNajmabadi Got it. I thought it was done in 17.8

**Comment by Compactis** [comment]
I still have a problem with null parameters

**Comment by jnm2** [comment]
17.9 is a long time to wait for this fix for many people who don't use previews. (I do, but I know many who have reasons not to.)

**Comment by jnm2** [comment]
Is there room for considering "debugger makes brand new feature confusing and hard to use" as critical?

**Comment by AlekseyTs** [comment]
> asking me if the feature is broken

Yes, an expression evaluation in debugger is broken for some scenarios. It does work for other scenarios. Runtime behavior of the feature is not affected. Meaning, the values are not what debugger displays in some scenarios.

**Comment by BernhardPollerspoeck** [comment]
> 17.9 is a long time to wait for this fix for many people who don't use previews. (I do, but I know many who have reasons not to.)

when i read this, i think about net 9 in november 2024.  
i hobe this is just a knownledge issue on my side, and its reasonable close.   
 

This being 'just' a debugger issue, might be correct and not an issue for the runtime, but just in case i remind: people are using the debugger to work on theyr code. and if the debugger doesnt work propperly here the whole feature is useless.  
  
So, my question here is: can anyone name a date(or time frame) when it is expected to be fixed in the release channel of VS22?

**Comment by BernhardPollerspoeck** [comment]
> > So, my question here is: can anyone name a date(or time frame) when it is expected to be fixed in the release channel of VS22?
> 
> No. We cannot comment on release dates as they may change at any point. What i can say is that 17.9 is already in public preview today, and is unrelated to .Net9. Thanks.

Thank you for the clarification. glas my first assumption is wrong. how long is a usual public preview? (are we talking days, weeks or month?).   
I totally understand, that you cant make a fixed date public.

**Comment by jnm2** [comment]
@BernhardPollerspoeck glancing back at the dates in the public release notes from 17.0 to 17.8, releases have so far been quarterly and 17.9 would be mid-February if it continues the pattern.

**Comment by DerAlbertCom** [comment]
Sadly, SDK 8.0.101 does not contain a fix for this issue.

It's very, very, very annoying that we can't trust the debugger on primary constructor parameters.

**Comment by CyrusNajmabadi** [comment]
@DerAlbertCom this reproes for you on the 17.9?

**Comment by TimWoerner** [comment]
Its marked as Closed but in latest Version (17.8.4) this bug is still there, so why is it closed? I don't have version 17.9 and do not want to use a preview version, so please put this "critical" bug in the 17.8.5
The feature that was released back in November is almost 2 months later not fixed

**Comment by CyrusNajmabadi** [comment]
> so why is it closed?

We close the bug once the code change for it has been made and incorporated into Roslyn. 

> I don't have version 17.9 and do not want to use a preview version

That's fine. I've you do upgrade, you should see the fix. 

> The feature that was released back in November is almost 2 months later not fixed

The issue has been fixed. Just that as with all fixes, it will make it in the next release of vs.  You can either get that fix now but using a preview, or choose to not do that and get the fix when the next non -preview version is released. 

Thanks!

**Comment by VivianRiver** [comment]
I have 17.8.6 and it's definitely not fixed in this version.

Please don't downplay how critical this is - I can't properly use the debugger with a major feature of the C# language.

Not critical?  I was excited to have a new feature to make it as easy to do dependency injection as it was with... (checks notes) AngularJS 1.x.

As a senior developer, I would be embarrassed to teach my junior developer workmates about this new feature that saves time and prevents errors, except, you can't debug it until 17.9 is released. 💩

That being said, it seems that this error reproduces in some, but not all circumstances.  At first, I thought it was something peculiar to dependency injection and Web API, but it seems that that is not the problem.  I suppose I'll simply avoid using this new feature until the bug is fixed.

**Comment by CyrusNajmabadi** [comment]
@VivianRiver can you supply a repro?

**Comment by ericbynum** [comment]
This is still broken in the latest version 17.8.6. Is there no plan to fix in a 17.8 patch?

**Comment by CyrusNajmabadi** [comment]
@ericbynum does this repro for you in 17.9.x?

**Comment by CyrusNajmabadi** [comment]
> I'll assume your response means it will not be patched in 17.8

The fix has been made, and will be rolled into the next version of VS (which is basically how practically all our fixes work).  You can use that fix now if you use the 17.9 line.  Thanks!

**Comment by VivianRiver** [comment]
I can confirm that 17.9 does fix the bug.

**Comment by enriqueraso** [comment]
Looks like in VS2022 17.14.9 has been broken again. It has been working fine in VS2022 17.12.7 @DerAlbertCom can you reopen this issue?

These are the list of sdks installed with VS2022 17.14.9

<img width="350" height="142" alt="Image" src="https://github.com/user-attachments/assets/a7c10f41-845b-4eea-82b9-a9e48a377078" />

and these are the list of sdks installed with VS2022 17.12.7

<img width="356" height="158" alt="Image" src="https://github.com/user-attachments/assets/55d6a249-02c6-449c-8e0d-f39ae8b1b0eb" />

**Comment by AlekseyTs** [comment]
> can you reopen this issue?

Please open a new issue with detailed information (repro steps, etc.).
