### ISSUE TITLE
[Test Failure] Test runner infrastructure failure in prtest/win/dbg/unit32 on PR #407

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn#7128]
PR: [#407](https://github.com/dotnet/roslyn-internal/pull/407) ** by @
Failure: http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_dbg_unit32/324/

**Issue 1: Test runner infrastructure failure**
The Test runner saw an exception that was neither a test failure nor a build failure and must have come from the test runner.

**Comment by davkean** [comment]
@brettfo Do you recognize this error:

```
The test runner has encountered a non-test-related exception.
11:31:53 To be clear, this is a problem with the test runner, not a test.
11:31:53 0a7ba10e-c611-4fb0-aefe-0c2efd6fe413
11:31:53 System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Could not find file 'd:\j\workspace\roslyn-internal_prtest_win_dbg_unit32\Open\Binaries\Debug\xUnitResults\APISampleUnitTestsVB.xml'.
11:31:53    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
11:31:53    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
11:31:53    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
11:31:53    at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy,
```

**Comment by brettfo** [comment]
I think @tyoverby was looking into this issue.

**Comment by TyOverby** [comment]
Yeah, I fixed this here: https://github.com/dotnet/roslyn-internal/pull/388

**Comment by TyOverby** [comment]
@davkean I think this should be investigated more.  It's really weird that we are still seeing the issue despite already being "fixed".

**Comment by davkean** [comment]
Can you point to more failures?

**Comment by TyOverby** [comment]
You mean other than this one?

**Comment by davkean** [comment]
You said we were still seeing this issue, can you point them out?

**Comment by TyOverby** [comment]
The build failure that this issue was created for.  http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_dbg_unit32/324/ happened _after_ my "fix".

**Comment by davkean** [comment]
Saw this issue again: http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_dbg_unit64/352/consoleFull#-911669781a937a245-1bcd-4648-b555-7d3e2507afd7.

@heejaechang Can you please invesigate?

**Comment by heejaechang** [comment]
dupe to https://github.com/dotnet/roslyn/issues/6843

it happens if mstest failures. don't know why msbuild failed.
