### ISSUE TITLE
MSBuildWorkspace.OpenSolutionAsync("My.slnx")

### ISSUE THREAD

**Issue by johnkors** [dotnet/roslyn#78097]
Should I expect the MSBuildWorkspace.OpenSolution methods to handle the new slnx-format, or is there a different API to open slnx?

**Comment by JoeRobich** [comment]
@johnkors If you have a new enough SDK (9.0.2xx) or MSBuild Tools (17.13) installed, it should work. We also [have a PR out](https://github.com/dotnet/roslyn/pull/77326) that will bring the support into Roslyn itself instead of relying on a particular MSBuild.

**Comment by johnkors** [comment]
I'm talking about the  `Microsoft.CodeAnalysis.MSBuild` ns from the `Microsoft.CodeAnalysis.CSharp.Workspaces` package. I'm using Roslyn for some CodeAnalysis integration tests that currently don't work with the new format. Will that PR end up in a new version of the `Workspaces` package?

**Comment by JoeRobich** [comment]
> I'm using Roslyn for some CodeAnalysis integration tests that currently don't work with the new format.

You may not be using a new enough SDK or MSBuild Tools then. 

> Will that PR end up in a new version of the Workspaces package?

Yes.

**Comment by johnkors** [comment]
It's not an SDK or MSBuild issue. Loading an sln in Rider and building in the terminal works just fine. 

I want to programatically load a solution using csharp, so I'll eagerly await the new Nuget with support for slnx.

```
        using var workspace = MSBuildWorkspace.Create();

        var solutionPath = GetSolutionPath();
        var solution = await workspace.OpenSolutionAsync(solutionPath);
        var documents = solution.Projects.SelectMany(c => c.Documents);
```

**Comment by JoeRobich** [comment]
> It's not an SDK or MSBuild issue. 

Sorry, I didn't mean at build time. MSBuildWorkspace uses the MSBuild from your SDK or MSBuild tooling to parse the solution file at runtime. If the version of MSBuild is new enough, then it will parse the slnx file for us.

Either way, this issue is resolved in https://github.com/dotnet/roslyn/pull/78647 by moving solution parsing to the new vs-solutionpersistence library.

**Comment by johnkors** [comment]
What does this mean, should I install another nuget to parse slnx-files? which? can you link to a nuget?

**Comment by johnkors** [comment]
The latest version https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp.Workspaces/4.14.0 still cannot read slnx-files.

**Comment by JoeRobich** [comment]
@johnkors As this change just merged, it is not in a release package. You can use the dotnet-tools feed to use a preview package containing this change. See https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet-tools/NuGet/Microsoft.CodeAnalysis.Workspaces.MSBuild/overview/5.0.0-1.25303.110 and follow the [suggested steps](https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet-tools/connect) to consume the feed.

**Comment by johnkors** [comment]
Ah ok, no worries. If I understood you correctly, v.5.0.0 of the nugets
- `Microsoft.CodeAnalysis.CSharp.Workspaces` 
- `Microsoft.CodeAnalysis.Workspaces.MSBuild` 

will have support for working with slnx-files.

I'll just wait for the release.
