### ISSUE TITLE
Is it possible for roslyn to support wasm as compiling target

### ISSUE THREAD

**Issue by Thaina** [dotnet/roslyn#8017]
In addition to IL I would like a C# compiler able to compile as WASM directly, not need any conversion from IL to WASM again (ilwasm also compile from C# -> IL -> JS -> WASM)

Is it possible?
Are there any C# feature missing from WASM?
Are there any wasm feature incapable to do from C#?

**Comment by benaadams** [comment]
(Referenced ilwasm https://github.com/WebAssembly/ilwasm)

**Comment by svick** [comment]
What would be the advantage of that? One of the big reasons IL exists is so that adding a support for new target platform can be easier and done once for all .Net languages.

**Comment by dsaf** [comment]
This is a dup of #3575.

@MadsTorgersen commented on WebAssembly recently: https://twitter.com/geertdoornbos/status/685183477969502212?lang=en

Sadly it doesn't seem to be a priority for Microsoft / .NET team but hopefully only for now. I personally think it would be a benefit to have C#-friendly full-time corporate-backed people collaborating on WebAssembly.

**Comment by Thaina** [comment]
@dsaf Thanks for you... I try to search the issue already but I don't know why I don't get any result

**Comment by dsaf** [comment]
@Thaina because we used different words: WASM vs WebAssembly :).

**Comment by Thaina** [comment]
@svick Actually what I mean is roslyn should add wasm emitter inside roslyn. Implementation may grab IL and convert to wasm or plugging in between at some point. I just want roslyn to include wasm as native target. Don't need to compile IL then grab another compiler to compile wasm

And I think we should plug wasm compiler after create syntax tree, after compile C# or VB but before IL, and emit wasm instead of IL, if possible

**Comment by dsaf** [comment]
Actually talking about IL doesn't make any sense, when this is happening:

https://msdn.microsoft.com/en-us/vstudio/dotnetnative.aspx

If making .NET Native C#-only is OK, then WASM should be addressed in a similar fashion. Thus satisfying the 95% of .NET developers (let's be honest).

**Comment by Thaina** [comment]
Now wasm is more promising day by day. Should have milestone for C# now

http://www.infoworld.com/article/3040037/javascript/webassembly-may-go-live-in-browsers-this-year.html

Also I don't know where it could ask but C# should prepare to support calling DOM and whole javascript library. I think I should ask in CoreCLR but C# still not directly support HTML platform yet

**Comment by juanfranblanco** [comment]
The potential for this is beyond limits for any .net language

**Comment by dsaf** [comment]
@juanfranblanco It seems that Xamarin will drag Microsoft into future kicking and screaming: https://twitter.com/migueldeicaza/status/735926391959617536

**Comment by Thaina** [comment]
@dsaf More like dragging while MS just sleeping and dream about one windows

**Comment by juanfranblanco** [comment]
From  Miguel https://twitter.com/migueldeicaza/status/739812829075755008

**Comment by Thaina** [comment]
Soon

http://www.infoworld.com/article/3137206/javascript/webassembly-now-available-as-release-candidate.html

**Comment by dsaf** [comment]
Related:

https://github.com/dotnet/llilc/issues/663
https://github.com/dotnet/llilc/issues/1067
https://github.com/Microsoft/ChakraCore/issues/1891

**Comment by Thaina** [comment]
Seem like xamarin team trying to do something related. I'm not sure what really is

https://github.com/xamarin/WebSharp

**Comment by Thaina** [comment]
http://www.androidpolice.com/2017/01/24/webassembly-enabled-default-chrome-58-gives-web-apps-processing-power/

**Comment by Thaina** [comment]
First true release on firefox

https://medium.com/mozilla-tech/why-webassembly-is-a-game-changer-for-the-web-and-a-source-of-pride-for-mozilla-and-firefox-dda80e4c43cb#.7zhcaf7l8

**Comment by Thaina** [comment]
Then Chrome now

https://www.bleepingcomputer.com/news/software/google-chrome-57-released-with-webassembly-support-36-security-fixes/

**Comment by morganbr** [comment]
We’ve started a WebAssembly experiment in the CoreRT repo and we need your help! Take a look at dotnet/corert#4659 for more details on what’s happening and how to get involved.

**Comment by CyrusNajmabadi** [comment]
Moving to runtime team.
